### ISSUE TITLE
Copy/paste is not working well in the GUI on the Windows version

### ISSUE THREAD

**Issue by kwarson** [vergecurrency/VERGE#249] opened 2018-01-02 02:57 UTC
In allmost all dialogs copy/paste is not working as expected.
You can't paste addresses in.
You can't copy addresses out.
Issue experienced on the windows version

**Comment by mybrainmelted** [comment] 2018-01-02 03:46
Cannot reproduce issue

Win 10 pro ver 1703 build 15063.786

VERGE-qt 4.0 v2.1.0.0-unk-beta

**Comment by vorlonempire** [comment] 2018-01-02 04:17
Ubuntu Cosmetic issue with right click #246

Can be related to this.

**Comment by kwarson** [comment] 2018-01-02 04:25
Win 10 Home Version 1709 build 16299.125
Ctrl-C/Ctrl-V doesn't work either.
VERGE-qt 4.0 v2.1.0.0-unk-beta

**Comment by mybrainmelted** [comment] 2018-01-02 06:33
Updated to Win 10 Pro ver 1709 build 16299.125

Still unable to reproduce your reported issue. 

Can right click and copy/paste as well as ctrl+c/ctrl+v. 

Granted you are on Win Home and not Pro, but your issue might be unrelated to GUI. Have you tested copy+paste with other software applications?

**Comment by justinvforvendetta** [comment] 2018-01-02 07:35
i cant reproduce this on linux or windows 10.

**Comment by rvrhee** [comment] 2018-01-02 07:44
still cannot resize debug window its way to big

**Comment by techpoy** [comment] 2018-01-02 08:06
I am not able to reproduce this on windows 10. copy/paste is working as expected
few things to note
1. Address field is disabled and empty when you create a New Receiving Address. you have to enter a label and click Ok and it will automatically generate an address for you.After creating new receiving address, you can only edit the label not the address
@justinvforvendetta option to remove an receiving address would be nice

2. From address book, you can double click on the rows to select the address/label or you can right click and you will get the context menu with  edit, copy address and copy label options. for address book entries, you can edit both label and address

**Comment by techpoy** [comment] 2018-01-02 08:10
@rvrhee I can confirm that this happens when the resolution is set to 1366x768 . When you resize the debug window at this resolution, the debug window's "Y" position drops to the bottom and disappears. There is no issue if i set the resolution back to 1920X1080. This is not happening with other windows (Main window & About Verge). This is not a severe bug though and resize option may be disabled to fix this.

**Comment by jrsikors** [comment] 2018-03-26 01:28
closing issue -- please re-open or open new issue if this is still a problem with the latest release

**Closed by jrsikors** 2018-03-26 01:28 UTC
