### ISSUE TITLE
Does the Verge team really develop XVG or make this coin by assembling the features from dead bodies???

### ISSUE THREAD

**Issue by kiennd** [vergecurrency/VERGE#304] opened 2018-01-03 10:24 UTC
Dear Verge Dev Team,
In fact is not any official communication channel between all people and the Verge team without this github. I know that posts in github are for the developers’ logs during the development phase but I don’t know anywhere to get the dev team’s answers so I’m sorry for my post here.

From the bottom of my heart **I have to publicize my doubts about your projects**.

When the first time I knew the Verge (XVG), I was really impressed by the Verge’s idea in a charge of Verge hodler and considered this project to be very promising. But **I have continually lost my faith in the Verge** because:
1.	There have been **a lot of problems in the quality of the Verge product**. I reviewed your recent codes committed on github, and I found that on 1/1/2018 you still make some codes that are gotten from some dead crypto projects. I wonder if the Verge dev team have made the Verge with a lot of bugs (https://github.com/vergecurrency/VERGE/issues?q=is%3Aopen+is%3Aissue) by collecting the features of the dead bodies???

a.	**Fantom**: https://coinmarketcap.com/currencies/fantomcoin/   ???
https://github.com/vergecurrency/VERGE/commit/51584d29e932ba6c576efeeff5fe14dfa74f6e2
Fantom is from here ???

![verge_1](https://user-images.githubusercontent.com/3886325/34516498-964e74aa-f0a9-11e7-8428-e06ed3f05ab2.png)

b.	**BottleCaps**: https://coinmarketcap.com/currencies/bottlecaps/ ???\
https://github.com/vergecurrency/VERGE/commit/0703eb9f3f3482656d2eed012ab1d32a3fe71c3f
 
![verge_2](https://user-images.githubusercontent.com/3886325/34516510-a00c7b5e-f0a9-11e7-9844-f374ba57c7c9.png)

c.	**ShadowCoin**: https://coinmarketcap.com/currencies/shadowcash/ ???
https://github.com/vergecurrency/VERGE/blob/8d1bd624c47f3c1643b137d2579d6766e8eae2ff/src/stealth.h
 
![verge_3](https://user-images.githubusercontent.com/3886325/34516516-a4ba96ea-f0a9-11e7-9b25-3fdf536ba148.png)

2.	There are a lot of ambiguity during the Verge release periods: the information is not consistent from your sources:
Everyone can see your github link https://github.com/vergecurrency/VERGE/releases
I don’t understand why you use ‘VVraith’ instead of ‘Wraith’ which is used in your road map and blackpaper, so why is the typo??? tricky???
 
![verge_4](https://user-images.githubusercontent.com/3886325/34516518-ac57f1f4-f0a9-11e7-82f8-9963357c4b1c.png)

Besides, as we know, your commitment is the Release 2’

**Plz give us the official announcement** instead of a lot of ambiguity with the answers from nickname VergeDev in your Discord (Where is the dev leader, sunerok with the nickname justinvendetta) , the unofficial words from the one called Verge Whale on twitter, ….???

Finally, thank you for your efforts in recent days. Have a nice day !

**Comment by sasasavic82** [comment] 2018-01-03 10:32
@kiennd ... you sound like an ant, trying to understand nuclear physics... or worse yet, an ant trying to lecture a nuclear physicist on how to build a nuclear reactor.

please do everybody a favour and close this ticket ... either help, or contribute in a meaningful way. if you're not sure about verge and the product, then sell your holdings and move on.

**Comment by kiennd** [comment] 2018-01-03 10:35
I just want to share the info to all people who have the right to know about this crypto

**Comment by rafaeloliveiras** [comment] 2018-01-03 10:38
Do you know what OPEN SOURCE means? Many coins share many techs in commom. Don't be a fool.. If a program or a part of it is OPEN, ANY DEV can USE the CODE. Facebok, YouTube and etc are a merge from many open sourced projects. Don't ask it again for anyone. OMG.

**Comment by tomazzaman** [comment] 2018-01-03 10:40
@kiennd reading your comments, I assume you're not a developer. If you were, you'd understand that not much code is written from scratch these days. There are frameworks that help us build software by using common best practices, libraries that we use _all the time_, because we don't need to write everything from scratch.

We also often look into other similar open source projects and take what we think fits our use cases.  So any developer, reading your doubts (which I think are sincere and not hateful), will only smile and move on, understanding what you do not.

**Comment by snoopy86** [comment] 2018-01-03 10:45
Just close this ticket. It is not worth even a comment.

**Comment by trolley0** [comment] 2018-01-03 10:47
@kiennd of course, no real development going on here, just code randomly copied from other projects to create the illusion. Glad you realized.

**Comment by dawi03** [comment] 2018-01-03 10:48
Wow...surely he's allowed to ask a bloody question without you lovers jumping down his throat. Great questions to be honest. As they have always made out they are building this themselves

**Comment by rafaeloliveiras** [comment] 2018-01-03 10:54
OMG what a fool people.. Bmw manufactor EVERY SINGLE PIECE OF A CAR? The Boeing and Embraer manufactor 100% of all pieces like avionics and etc? The answer is NO. For god sake..

**Comment by mnott** [comment] 2018-01-03 10:54
Actually, I think it deserves a comment. For once, just because I'm a developer and researcher myself, I very much am interested on which shoulders a project is standing. As a non-developer, I'd be rightly concerned seeing things that from the outside look like simple code copy/paste. That has the potential to create FUD.

A good practice from the research community would be to reference openly what was reused, i.e. to give credit to original writers; and then also to clearly state the contribution of the project. For example, there is ZEC.X (and of which the price we'd probably all want to see here at some point), and it also claims to have a stealth feature. What is the difference?

Otherwise saying, we should not complain about FUD about: People have (albeit hopefully only temporarily) written off serious amounts of money. That makes them angry. Rather than shutting them off, this project here should clearly have a marketing - and more generally, documentation - strategy that is proactive, rather than reactive.

At this moment, all I get with Verge is a wallet that doesn't synchronize (and no firewall in between), that has very basic UI glitches (like the language dropdown), and that I need to compile from source, which in addition entails a whole set of additional steps. That's not a delivered product, it's something in development. I can live with that (also because I don't currently need the about 40k USD that I've dumped into this project, so I can wait).

An ex-boss of mine once said, I don't understand the fundamentals of software sales when I was asking why are we selling something that I, as the developer, know does not exist yet. It's not about having the product, it's about selling it.

I'm not suggesting not to do anything here, but I do suggest to get a lot better on the sales side. Bear in mind, second-best products tend to be the survivors.

**Comment by fr4z3n** [comment] 2018-01-03 10:56
@kiennd 
Okay I understand your concerns.

I developed many years on WoW emulated servers. It's also based on opensource. There are many projects and some are better, some are worse. It's the same in crypto-development.
Everything is opensource - some are good, some are bad.

Firstly you adress the issue of the quality. The quality is not bad because of the underlying sourcecodes, it is because it was rushed to be released and many bugs were discovered after the release. This is NORMAL for an opensource project! Because there is no tester team. (most of the time)

Secondly you adress that sourcecode is taken from "dead" projects. Well they might be dead, because their vision was not good enough, but the sourcecode might be great. I know that!
So I'm not going further down with your listing of the dead bodies.

Third you adress the issue that in the release period there was no consistent information:
Yes I can confirm this and would like to see some improvments there.
The community is going on github and searching for news, but many of the users don't understand the development and waiting for travis builds which means nothing.
I would like to have consistent news between twitter / facebook / website, when a release is done.

Thank you for reading.

**Comment by sasasavic82** [comment] 2018-01-03 11:04
^^^ what he said

**Comment by kiennd** [comment] 2018-01-03 12:16
If you are developers, you will understand my words when looking into the source codes :). 

In the software development, the product need to be tested successfully before releasing a version for public. But until know, although announcing the 'VVraith Release 2' (not 'Wraith Release 2) unofficially, there have bean a lot of basic errors in coding, and no commitment with the deadline (1/1/2018), unplanned :D, who knows when the wraith works well??? the dev leader Sunerok (justinvendetta), XVGWhale, McAffee or someone else can answer us???

Really unprofessionally in the Verge team :) Plz listen to me :D I don't intend to ruin the Verge but I think my info really helps you, HODLERS, INVESTORS and Verge FANS :)

Plz don't deceive yourself and looking into the truth :)

**Comment by fr4z3n** [comment] 2018-01-03 12:20
Okay, we tried to explain it to you, but you have no clue of development. And no clue about opensourceprojects.

Your answer is not valuable to me because of your smilies and overused questionmarks.

Best regards

**Comment by kiennd** [comment] 2018-01-03 12:24
@fr4z3n: I have some emotions because I feel funny when you don't want to see the truth. You want we deceive together about something bad.

**Comment by fr4z3n** [comment] 2018-01-03 12:29
You are referring to software development and it has to be tested.
Did you ever work as a developer? 
I know how the code looks and can understand the commithistory. I'm not amused by what I see but I can understand the developer.
I'm not amused but I'm used to it. This is opensource and not a mainstream company. Therefore I believe in the potential.

**Comment by TheOwlie** [comment] 2018-01-03 12:31
Having been a coder for 20 years I can second what @fr4z3n said. 

In any product there is reused code. (all websites, all apps on the internet use third party libraries and open source frameworks). If you would to reinvent the wheel every time you code.. you would be years left behind so no coder does that anymore. I'm content with 20% being own code.

And to remind people this isn't a well oiled release process company, and they do not have any great marketing team (yet), but neither was any 5 man team from the beginning. Next release they will have learned and more people on board to help with that process. 

Writing 100% coverage tests is more or less impossible (at least on a 5 man team), sometimes it's better to release fast and rely on users for quick feedback (but making sure basics works which they missed on one bug IMHO, but that they also solved). 

If you do not know the basics of product development and especially a release process. Just get out and invest in Verge when you think it's ready enough, you won't get as much out of it as someone with knowledge of the prior.. but you can feel safe if that's your main concern.

I got a working version in under 3 days after deadline, I'd say that is pretty good on a second version of a product.

Also @kiennd just stop trolling, you obviously don't have enough knowledge about anything above here... and then you do not hold the truth.

Now just close this issue, since it's not an issue.

**Comment by fr4z3n** [comment] 2018-01-03 12:34
@TheOwlie well said. Nothing more to add.

**Comment by kiennd** [comment] 2018-01-03 12:44
@tomazzaman tom
I am developer and I know that developers like me reuse source codes to make a project.
As you know, we need polish our products and make it the best as we can before publicizing a release of the product, right? And you can see the carelessness of the dev, why there is still the name of another dead project in the committed code. What's the hell? This shows not good and careless developers, right??? so who commits the quality of the Verge (XVG) projects and make a warranty for your XVG coins????? You want someday your coins to be disappeared with no reason???

![34516510-a00c7b5e-f0a9-11e7-9844-f374ba57c7c9](https://user-images.githubusercontent.com/3886325/34520960-bf97d3ec-f0bd-11e7-970d-3692ca960ba8.png)

**Comment by satrya-sabeni** [comment] 2018-01-03 13:13
@kiennd Yes, it's the release was earlier than ideal but at the same time the deadline really needed be met this time. Look at the work that's been pushed out the last 2 days, obviously they're working very hard to polish it. You can see the code that needs to be be updated, being updated. You expect them to completely reinvent the wheel again when it's already there? It's part of the game, adopt what you can, adjust it to your own project and make it better, that's how it's always been.

**Comment by akvn90** [comment] 2018-01-03 13:16
@kiennd  You said:" why there is still the name of another dead project in the committed code"
The codes in Red Color are the **ORIGINAL** codes.
They were replaced with the **NEW** codes in Green Color.
Github keeps the old code so that developers can see which line was changed in a commit. All the other **dead project**  name has been replaced.  
Please don't pretend that you are developer. You know nothing about open source.

**Comment by sasasavic82** [comment] 2018-01-03 13:44
he's trolling.. close this issue

**Closed** 2018-01-03 13:56 UTC

**Comment by justinvforvendetta** [comment] 2018-01-03 14:25
monero is forked from bytecoin https://github.com/monero-project/monero/commit/84ca73ea77d50815dd6ce087c8b65980d6c2d2c3#diff-04c6e90faac2675aa89e2176d2eec7d8

zcash is forked from bitcoin, and so on... 

maybe you dont understand how this works because the most complex thing in your repository is a sudoku game.
