### ISSUE TITLE
0 active connections

### ISSUE THREAD

**Issue by ryc617** [vergecurrency/VERGE#727] opened 2018-04-18 07:29 UTC
I download the new version  v4.0.2.0-c3a04c0-funky-beta, but there is no active connections. 
Who can help me ,thanks.

This is my log file content:

VERGE version v4.0.2.0-c3a04c0-funky-beta (2018-04-12 06:06:47 +0000)
Using OpenSSL version OpenSSL 1.0.2k  26 Jan 2017
Startup time: 04/18/18 05:44:58
Default data directory C:\Users\sigma\AppData\Roaming\VERGE
Default mining hash algorithm: scrypt
Used data directory C:\Users\sigma\AppData\Roaming\VERGE
scrypt: using scrypt-sse2 as detected.
dbenv.open LogDir=C:\Users\sigma\AppData\Roaming\VERGE\database ErrorFile=C:\Users\sigma\AppData\Roaming\VERGE\db.log
Bound to 127.0.0.1:21102
TOR thread started.
AddLocal(7p4aoqgvnm6f2gip.onion:21102,4)
Loading block index...
Opening LevelDB in C:\Users\sigma\AppData\Roaming\VERGE\txleveldb
Transaction index version is 70509
Opened LevelDB successfully
No OBFS4 found, not using it.
LoadBlockIndex(): hashBestChain=1f99a3c2256c35220361988b61d8625d38832f77403761402e42e692460d9a0a  height=2065302  trust=2065303  date=04/16/18 23:55:35
LoadBlockIndex(): synchronized checkpoint 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
Verifying last 2500 blocks at level 1
 block index         4719864ms
Loading wallet...
nFileVersion = 4000200
 wallet                  240ms
Rescanning last 191 blocks (from block 2065111)...
 rescan                  765ms
Loading addresses...
Loaded 6448 addresses from peers.dat  131ms
mapBlockIndex.size() = 2090951
nBestHeight = 2065302
setKeyPool.size() = 101
mapWallet.size() = 4
mapAddressBook.size() = 2
Done loading
Loading addresses from .onion seeds
ThreadSocketHandler started
ThreadMessageHandler started
Added 7sfrhwc6l4oohb5h.onion:21102 from 7sfrhwc6l4oohb5h.onion: 623 tried, 5825 new
Added ie4vffvggaz6xhbj.onion:21102 from ie4vffvggaz6xhbj.onion: 623 tried, 5825 new
Added kw5bdikypbbxaf2g.onion:21102 from kw5bdikypbbxaf2g.onion: 623 tried, 5826 new
Added n5ln6ke2vc47glpl.onion:21102 from n5ln6ke2vc47glpl.onion: 623 tried, 5827 new
7 addresses found from .onion seeds
ThreadOnionSeed exited
Flushed 6450 addresses to peers.dat  156ms
refreshWallet
ipcThread started
trying connection o7dw7csxrxo5ise4.onion:21102 lastseen=36.8hrs
SOCKS5 connecting o7dw7csxrxo5ise4.onion
ERROR: Error reading proxy response
trying connection wckqtqw64bwzkdot.onion:21102 lastseen=38.3hrs
SOCKS5 connecting wckqtqw64bwzkdot.onion
ERROR: Error reading proxy response
trying connection dryryhio74utdyrl.onion:21102 lastseen=38.5hrs
SOCKS5 connecting dryryhio74utdyrl.onion
ERROR: Error reading proxy response
trying connection o6lqzh4h3v4kxe47.onion:21102 lastseen=33.9hrs
SOCKS5 connecting o6lqzh4h3v4kxe47.onion
ERROR: Error reading proxy response
trying connection jb4uoeqbxk7c5ibx.onion:21102 lastseen=124.4hrs
SOCKS5 connecting jb4uoeqbxk7c5ibx.onion
ERROR: Error reading proxy response
trying connection m3a675vni346yjad.onion:21102 lastseen=41.5hrs
SOCKS5 connecting m3a675vni346yjad.onion
ERROR: Error reading proxy response
trying connection yu4zke54lq35ojpt.onion:21102 lastseen=39.1hrs
SOCKS5 connecting yu4zke54lq35ojpt.onion
ERROR: Error reading proxy response
trying connection pwepw6ljnqo274s2.onion:21102 lastseen=45.8hrs
SOCKS5 connecting pwepw6ljnqo274s2.onion
ERROR: Error reading proxy response
trying connection j47fajwp46o3htze.onion:21102 lastseen=31.3hrs
SOCKS5 connecting j47fajwp46o3htze.onion
ERROR: Error reading proxy response
trying connection d7bdkiybdmhamkpt.onion:21102 lastseen=43.4hrs
SOCKS5 connecting d7bdkiybdmhamkpt.onion
ERROR: Error reading proxy response
trying connection bmitouzjjjlkqp3n.onion:21102 lastseen=32.0hrs
SOCKS5 connecting bmitouzjjjlkqp3n.onion
ERROR: Error reading proxy response
trying connection 73kmadtaz353n6xe.onion:21102 lastseen=34.1hrs
SOCKS5 connecting 73kmadtaz353n6xe.onion
ERROR: Error reading proxy response
trying connection vbgcgkywjypscdpn.onion:21102 lastseen=38.3hrs
SOCKS5 connecting vbgcgkywjypscdpn.onion
ERROR: Error reading proxy response
trying connection 6qqzhu3buw3sripb.onion:21102 lastseen=272.8hrs
SOCKS5 connecting 6qqzhu3buw3sripb.onion
ERROR: Error reading proxy response
trying connection cx3q7unquffwudno.onion:21102 lastseen=54.2hrs
SOCKS5 connecting cx3q7unquffwudno.onion
ERROR: Error reading proxy response
trying connection weqgy33cjjbhto55.onion:21102 lastseen=35.6hrs
SOCKS5 connecting weqgy33cjjbhto55.onion
ERROR: Error reading proxy response
trying connection iavmwvmvejhlmwm3.onion:21102 lastseen=44.8hrs
SOCKS5 connecting iavmwvmvejhlmwm3.onion
ERROR: Error reading proxy response
trying connection 42qt4xpgbdg3ylwf.onion:21102 lastseen=34.3hrs
SOCKS5 connecting 42qt4xpgbdg3ylwf.onion
ERROR: Error reading proxy response
trying connection gjwmcv6wmyyicsjn.onion:21102 lastseen=113.2hrs
SOCKS5 connecting gjwmcv6wmyyicsjn.onion
ERROR: Error reading proxy response
trying connection ptwdpeejh4hicdvh.onion:21102 lastseen=41.1hrs
SOCKS5 connecting ptwdpeejh4hicdvh.onion
ERROR: Error reading proxy response
trying connection df5ec4xrhg2fd23i.onion:21102 lastseen=44.2hrs
SOCKS5 connecting df5ec4xrhg2fd23i.onion
ERROR: Error reading proxy response
trying connection jkdcotg35i7m7v4i.onion:21102 lastseen=42.0hrs
SOCKS5 connecting jkdcotg35i7m7v4i.onion
ERROR: Error reading proxy response
trying connection zqdljeuuviegelgl.onion:21102 lastseen=39.3hrs
SOCKS5 connecting zqdljeuuviegelgl.onion
ERROR: Error reading proxy response
trying connection npcth6gliue5hj4i.onion:21102 lastseen=206.6hrs
SOCKS5 connecting npcth6gliue5hj4i.onion
ERROR: Error reading proxy response
trying connection yjsp2ysfyymyz47q.onion:21102 lastseen=41.4hrs
SOCKS5 connecting yjsp2ysfyymyz47q.onion
ERROR: Error reading proxy response
trying connection bbnzzk2pnpzt2g7r.onion:21102 lastseen=31.8hrs
SOCKS5 connecting bbnzzk2pnpzt2g7r.onion
ERROR: Error reading proxy response
trying connection dg25v5ua5ib4w2uz.onion:21102 lastseen=35.6hrs
SOCKS5 connecting dg25v5ua5ib4w2uz.onion
ERROR: Error reading proxy response
trying connection otuodmn6k6yfrwjg.onion:21102 lastseen=47.2hrs
SOCKS5 connecting otuodmn6k6yfrwjg.onion
ERROR: Error reading proxy response
trying connection bcxah4hpj336thff.onion:21102 lastseen=36.0hrs
SOCKS5 connecting bcxah4hpj336thff.onion
ERROR: Error reading proxy response
trying connection z5e6hyytktfv6gby.onion:21102 lastseen=183.0hrs
SOCKS5 connecting z5e6hyytktfv6gby.onion
ERROR: Error reading proxy response
trying connection btafa35vjuqff4kn.onion:21102 lastseen=47.0hrs
SOCKS5 connecting btafa35vjuqff4kn.onion
Flushed 6450 addresses to peers.dat  222ms
ERROR: Error reading proxy response
trying connection 4xi275wqjgzhhdvy.onion:21102 lastseen=41.7hrs
SOCKS5 connecting 4xi275wqjgzhhdvy.onion
ERROR: Error reading proxy response
trying connection xkxrzobnei4cwasi.onion:21102 lastseen=41.9hrs
SOCKS5 connecting xkxrzobnei4cwasi.onion
ERROR: Error reading proxy response
trying connection dckpz4bcoi5tniea.onion:21102 lastseen=46.8hrs
SOCKS5 connecting dckpz4bcoi5tniea.onion
ERROR: Error reading proxy response
trying connection iwaekwjfsgtqj6hz.onion:21102 lastseen=33.6hrs
SOCKS5 connecting iwaekwjfsgtqj6hz.onion
ERROR: Error reading proxy response
trying connection o7ih6hkv7zfhpz2e.onion:21102 lastseen=105.4hrs
SOCKS5 connecting o7ih6hkv7zfhpz2e.onion
ERROR: Error reading proxy response
trying connection ccm6kdxucwt64mwj.onion:21102 lastseen=45.9hrs
SOCKS5 connecting ccm6kdxucwt64mwj.onion
ERROR: Error reading proxy response
trying connection fwhq4ptipxgd5upn.onion:21102 lastseen=71.0hrs
SOCKS5 connecting fwhq4ptipxgd5upn.onion
ERROR: Error reading proxy response
trying connection oqlgzw75cwdhm7ya.onion:21102 lastseen=37.3hrs
SOCKS5 connecting oqlgzw75cwdhm7ya.onion
ERROR: Error reading proxy response
trying connection gnajetrwdopjyofg.onion:21102 lastseen=37.3hrs
SOCKS5 connecting gnajetrwdopjyofg.onion
ERROR: Error reading proxy response
trying connection nt5r5y5wplswyfie.onion:21102 lastseen=43.4hrs
SOCKS5 connecting nt5r5y5wplswyfie.onion
ERROR: Error reading proxy response
trying connection 3dsmr6bzj6cak6gw.onion:21102 lastseen=38.2hrs
SOCKS5 connecting 3dsmr6bzj6cak6gw.onion
ERROR: Error reading proxy response
trying connection kfdpocr74zxrf62l.onion:21102 lastseen=36.8hrs
SOCKS5 connecting kfdpocr74zxrf62l.onion
ERROR: Error reading proxy response
trying connection exhd6vecnnelvv2s.onion:21102 lastseen=49.4hrs
SOCKS5 connecting exhd6vecnnelvv2s.onion
ERROR: Error reading proxy response
trying connection acs4p5xxrevevzsu.onion:21102 lastseen=85.8hrs
SOCKS5 connecting acs4p5xxrevevzsu.onion
ERROR: Error reading proxy response
trying connection 5yrtvnerhd3s3v2j.onion:21102 lastseen=40.5hrs
SOCKS5 connecting 5yrtvnerhd3s3v2j.onion
ERROR: Error reading proxy response
trying connection 2yyofhielr7nb22n.onion:21102 lastseen=34.0hrs
SOCKS5 connecting 2yyofhielr7nb22n.onion
ERROR: Error reading proxy response
trying connection h3korhk6wmrd3v5h.onion:21102 lastseen=36.8hrs
SOCKS5 connecting h3korhk6wmrd3v5h.onion
ERROR: Error reading proxy response
trying connection dw4ab6zjy44liu65.onion:21102 lastseen=41.3hrs
SOCKS5 connecting dw4ab6zjy44liu65.onion
ERROR: Error reading proxy response
trying connection 3g2a2tsovlk33p6e.onion:21102 lastseen=37.9hrs
SOCKS5 connecting 3g2a2tsovlk33p6e.onion
ERROR: Error reading proxy response
trying connection hlz7kbsnbwdwg4vz.onion:21102 lastseen=39.9hrs
SOCKS5 connecting hlz7kbsnbwdwg4vz.onion
ERROR: Error reading proxy response
trying connection 3p2f5udyg6zlrmjk.onion:21102 lastseen=40.3hrs
SOCKS5 connecting 3p2f5udyg6zlrmjk.onion
ERROR: Error reading proxy response
trying connection empszfgec5ku2mes.onion:21102 lastseen=38.7hrs
SOCKS5 connecting empszfgec5ku2mes.onion
ERROR: Error reading proxy response
trying connection ol4egz7pgzw63zmy.onion:21102 lastseen=43.5hrs
SOCKS5 connecting ol4egz7pgzw63zmy.onion
ERROR: Error reading proxy response
trying connection hwdkjfxgn2uomite.onion:21102 lastseen=37.1hrs
SOCKS5 connecting hwdkjfxgn2uomite.onion
ERROR: Error reading proxy response
trying connection pilsxdlpct3a5wq3.onion:21102 lastseen=46.7hrs
SOCKS5 connecting pilsxdlpct3a5wq3.onion
ERROR: Error reading proxy response
trying connection ttvrhxqwjw425exd.onion:21102 lastseen=45.0hrs
SOCKS5 connecting ttvrhxqwjw425exd.onion
ERROR: Error reading proxy response
trying connection kr5ui6jkggxh4yno.onion:21102 lastseen=59.1hrs
SOCKS5 connecting kr5ui6jkggxh4yno.onion

**Comment by jrsikors** [comment] 2018-04-18 14:10
try closing down verge-qt.

Go to your data directory:
 C:\Users\sigma\AppData\Roaming\VERGE

delete peers.dat

re-open verge-qt

also check out:
https://github.com/vergecurrency/VERGE/wiki/Verge-QT-Wallet-FAQ-&-Common-Issues

for other tips

**Comment by ryc617** [comment] 2018-04-19 10:13
![1](https://user-images.githubusercontent.com/38489277/38985892-408963c0-43fd-11e8-8ed2-416a7fbf0005.png)

No active connection.

**Comment by jrsikors** [comment] 2018-04-19 14:59
Are you in China or a country that blocks Tor?

Please look into issue #719 

I know there hasn't been an official "fix" yet .. but if you are good with Tor you might be able to help figure out the solution

**Comment by jrsikors** [comment] 2018-04-21 15:57
closing this as a duplicate of #719   ... plz follow along and 'subscribe' to notifications on #719

**Closed by jrsikors** 2018-04-21 15:57 UTC
Labels: help wanted
