### ISSUE TITLE
Problem with Address in Wallet 

### ISSUE THREAD

**Issue by sybit88** [vergecurrency/VERGE#98] opened 2017-11-21 05:48 UTC
I tried the upgrade to load the blockchain and that really didn't work.  I had sent XVG to the wallet before the wallet synced (I know, my fault).  Then, I tried to upgrade the wallet and I cannot use the same receiving address for my XVG from Bittrex.  I can change the label but not the receiving address.  In the process of the upgrade, i have not received my coins.  Help.

sybit88

**Comment by londoncoingatherer** [comment] 2017-12-23 16:38
Did you get anywhere with this? I've got a similar issue

**Comment by justinvforvendetta** [comment] 2017-12-24 18:18
you can create a new address, I'm not sure what you're saying. can you clarify please

**Comment by londoncoingatherer** [comment] 2017-12-24 19:43
How would I create a new address?

When I first downloaded the verge QT it connected and the progress bar at the bottom started moving, but it only loaded a tiny bit and since then it won’t connect at all.

I’ve tried turning off the firewall, I’ve tried deleting it and re-installing, ive tried the electrum wallet instead and I’ve tried to add the block chain (but there is no verge folder in my application support folder on Mac). But none of these things have worked.

So I’m running out of ideas.. any help would be most appreciated! And sorry if my explanations aren’t great, I’m only a little tech savvy..

On 24 Dec 2017, at 18:18, sunerok <notifications@github.com<mailto:notifications@github.com>> wrote:


you can create a new address, I'm not sure what you're saying. can you clarify please

**Comment by HumphreyPloughjogger63** [comment] 2017-12-28 00:19
Any luck? Same problem here.

**Comment by edpark722** [comment] 2017-12-28 00:21
I've been using the electrum-xvg wallet without issues.  Try using that one.  They've recently added more servers as the old ones were overloaded.  Check out @vergecurrency for the latest servers.

**Comment by londoncoingatherer** [comment] 2017-12-28 12:23
All working fine now with the electrum wallet!

On 28 Dec 2017, at 00:22, Edmund Park <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been using the electrum-xvg wallet without issues. Try using that one. They've recently added more servers as the old ones were overloaded. Check out @vergecurrency<https://github.com/vergecurrency> for the latest servers.

**Comment by HumphreyPloughjogger63** [comment] 2017-12-28 20:59
Ok so after a ton of research this is what I’ve found:

The problem is the wallet.dat file. The original address and private key was overwritten when we downloaded the blockchain; to recover the private key to the original address and thereby recover our coins we need to recover a previous version of that file. I’ve ran a couple different recovery programs to no avail...they’d work great if you simply lost  the file, but not so much with overwritten files. If you didn’t choose to replace when you moved the blockchain file you should be able to recover them this way. 

I’ve been using pywallet (for bitcoin, not sure if it’s compatible it’s xvg) in terminal, but no luck so far. Next I’m installing Linux and trying to run a script that identifies private keys by known proximity markers. 

Sorry if some of the terminology isn’t precise, I’m new to all of this. Never dug more than facial depth in anything computer related. But this screw up is actually benefitting me, I’m learning a ton. Standby for updates of any change in my situation.

**Comment by mikericho** [comment] 2018-01-03 09:11
Hi Humphrey i had exactly the same problem on my mac ,sent coins before syncing, i have tried everything resending / private key but still no avail have you been able to solve the problem with the wallet.dat file.

**Comment by joem789** [comment] 2018-01-26 22:11
Having the same problem today. Sent XVG to the same wallet address I always use. But it still shows address not found on blockchain explorer. Binance still shows transaction "processing". Verge seems to be the only one I have this trouble with.

**Comment by justinvforvendetta** [comment] 2018-01-26 22:14
binance is on the latest update (im pretty sure) verge-blockchain.info is definitely on the latest block.

the address you always use, should show up on the explorer. i havent seen anything like that before.

**Comment by Paapo** [comment] 2018-01-28 12:09
Hi, it looks like, i´ve a semilar issue. I´ve used V3.0 all the time, without any issues. On Wednesday, i´ve updated to version 4.0.1 now. Before, i´ve saved my wallet.dat. After updating to version 4 and loading the old wallet.dat, it has displayed my current amount fine. Then he connected to the network and began to synch. Verry slow, but it synched. I thought al was good. Next morning, the wallet has shows it is synched. Both sighns "out of synch" were gone, no green status were shown. So i thought all is fine and i´ve created a new non stealth wallet address. After this, i´ve saved the wallet.dat again.Then i made 3 transactions from cryptopia. 2 was send to my old address (1. Amount 5 xvg, 2. Amount 17K). The first transaction i can see in the blockexplorer and it was shown, after a while as an unconfirmed transaction, in my wallet. Again i thought all ist fine. Then i send the secomd transaction. This one is showing with an error message in the blockexplorer. Since then, i was aare, there is something wrong with the synch. Now I´m unable to synch my wallet. I´ve tons of connections, but there is no progress- I´ve about 7K blocks left, and nothing happens. Green Status Bar is comming and going. I tried it with several of my wallet.dats. Downloading the full blockchain also. But it always stopps, after a while.

Can somebody please help, to get my coins back into the wallet. That is really a nightmare:-(

Regards,
MArcus

**Comment by erawed** [comment] 2018-01-29 02:06
Tried to install the verge core, but the synch was too slow (few days still less 50%) and I decided to use electrum one. But it, as I understand now, doesn't work. Initially I got just an error, after 1st reinstalling I have a bug during retyping a seed (button "next" didn't get activated. I tried 2 times.) Few days later I decided to check maybe smth was fixed and download again and now I have the error as when my first attempt))  "Okay.."- I think, - Let's try core again".So I saved the core wallet , the last blockchain and followed the [instructions](https://drive.google.com/file/d/1KxIfooNfgRIghWXvndeyQFkz6bD9yOVr/view) from their website. But there is the step to find the verge folder in the Application support. I have nothing even similar. So, verge devs or any contributors, please, fix it ASAP or tell us what we should do. Thanks

**Comment by Influence2** [comment] 2018-01-31 21:50
This issue seems to be just a area for multiple issues across multiple wallets and OS's. 

1. If you are using the Core Wallet make sure you let it fully sync before performing actions. This seems to avoid many issues.

2. Always keep a backup of your wallet.dat.

I think this issue should be closed by the OP, and each person should open their own issue. @sybit88

**Closed** 2018-02-01 00:11 UTC
