### ISSUE TITLE
problem with decoding transaction in new Windows wallet

### ISSUE THREAD

**Issue by JSBachForSoulCleansing101** [vergecurrency/VERGE#413] opened 2018-01-09 01:53 UTC
When decoding transactions in new windows 4.0.1 wallet...wrong amounts seen and transaction fees are the same as the transfer amounts...both of which are wrong

# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment] 2018-01-09 02:11
what do you mean "wrong amounts seen" can you post some screenshots? i cant reproduce that

**Comment by zsuerdieck** [comment] 2018-01-09 04:15
I tested with 5 transactions and one looked like described above. Transaction 5cbd7242202e223166c4b11c38fd6ebd59bbb30cdf3bcbed8e752769497480f4
Value out and Fees are the same

**Comment by justinvforvendetta** [comment] 2018-01-09 04:23
was this the new release from tonight? was that a stealth tx? can you provide some context?

**Comment by justinvforvendetta** [comment] 2018-01-09 04:24
it looks normal on the explorer, so maybe its just an issue with the explorer parsing https://verge-blockchain.info/tx/5cbd7242202e223166c4b11c38fd6ebd59bbb30cdf3bcbed8e752769497480f4

**Comment by zsuerdieck** [comment] 2018-01-09 04:26
The transaction was from 4 days ago. I'm using the new release to decode transaction though

**Comment by justinvforvendetta** [comment] 2018-01-09 04:27
oh i see. ok let me take a look.

**Comment by JSBachForSoulCleansing101** [comment] 2018-01-09 04:47
Hi Justin....Thanks for your vision and dedication!
The actual transaction was for 10 xvg coins....sent to a friends binance xvg wallet



    On Monday, January 8, 2018, 8:24:34 PM PST, sunerok <notifications@github.com> wrote:  
 
 
it looks normal on the explorer, so maybe its just an issue with the explorer parsing https://verge-blockchain.info/tx/5cbd7242202e223166c4b11c38fd6ebd59bbb30cdf3bcbed8e752769497480f4

**Comment by JSBachForSoulCleansing101** [comment] 2018-01-09 04:50
![image](https://user-images.githubusercontent.com/34946186/34705310-7b5a0de4-f4b4-11e7-896e-7b855c83c895.png)

**Comment by justinvforvendetta** [comment] 2018-01-09 05:38
yeah I'm taking a look. your friend received the proper amount right?

**Comment by JSBachForSoulCleansing101** [comment] 2018-01-09 08:11
Yes

**Comment by jrsikors** [comment] 2018-03-26 01:20
closing issue -- please re-open or open new issue if this is still a problem with the latest release

**Closed by jrsikors** 2018-03-26 01:20 UTC
