### ISSUE TITLE
When editting a stealth address checkbox is not checked

### ISSUE THREAD

**Issue by modislaszlo** [vergecurrency/VERGE#440] opened 2018-01-10 19:57 UTC
After creating a new stealth address if you edit it the checkbox is not checked.

**Comment by fabiotnt** [comment] 2018-01-12 18:35
Confirmed at v4.0.1. Same issue here.

**Comment by marpme** [comment] 2018-01-12 22:16
Dunno if this should be unchangeable at all. Maybe we can just disable the button for normal and for stealth address editing since it should be decided at the creation. Am I right at this ? @justinvforvendetta

**Comment by modislaszlo** [comment] 2018-01-13 10:08
In my opinion it should be disabled and show that is stealth address(checkbox should be checked); The name/address format maybe is not enough for some people to know that that address is a stealth one.

**Comment by jrsikors** [comment] 2018-03-27 00:48
@justinvforvendetta @michpiatek this is confirmed still an issue in funky beta btw.  Unsure if you resolved since then.

**Comment by jrsikors** [comment] 2019-01-18 17:11
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.

**Closed by jrsikors** 2019-01-18 17:11 UTC
Labels: bug, cosmetic issue
