### ISSUE TITLE
Debug window to big and disappears

### ISSUE THREAD

**Issue by rvrhee** [vergecurrency/VERGE#217] opened 2018-01-01 17:23 UTC
Debug window to big and disappears

windows 10

**Comment by justinvforvendetta** [comment] 2018-01-01 17:25
disappears? can you clarify. i cant reproduce it disappearing.

**Comment by KnightOwl47** [comment] 2018-01-01 17:25
working fine for me.

**Comment by vorlonempire** [comment] 2018-01-01 17:26
As to "to big" yes, it looks llike twice the volume of space larger than the wallet

**Comment by rvrhee** [comment] 2018-01-01 17:40
When i try to resize it disappears  its not in the task bar and not in alt-tap.....

**Comment by vorlonempire** [comment] 2018-01-01 17:55
i cannot reproduce disappearing also

**Comment by justinvforvendetta** [comment] 2018-01-01 18:09
@rvrhee can you tell us what operating system you are using? and which version of the wallet?

**Comment by rvrhee** [comment] 2018-01-01 18:17
windows 10 pro  v2.1.0.0-unk-beta can't resize the debug window when i do that it scrolls to nowhere its gone tried it now four times its just gone. 1366x768 screen resolution

**Comment by mybrainmelted** [comment] 2018-01-01 18:19
Using Win10 x64, Verge-qt 4.0

Cannot reproduce issue with debug window disappearing, but can confirm that vertical size of debug window is larger than wallet and is unable to be resized, through either vertical/diagonal resize. Horizontal resize works OK.

**Comment by mybrainmelted** [comment] 2018-01-01 18:22
^*Win 10 Pro x64 ver 1703 build 15063.786

**Comment by justinvforvendetta** [comment] 2018-01-01 18:24
yeah i dont have a disappearing debug window on linux or windows. closing since i cant reproduce.

**Closed by justinvforvendetta** 2018-01-01 18:24 UTC

**Comment by techpoy** [comment] 2018-01-01 18:59
I can confirm that this happens when the resolution is set to 1366x768 . When you resize the debug window at this resolution, the debug window's "Y" position drops to the bottom and disappears. There is no issue if i set the resolution back to 1920X1080. This is not happening with other windows (Main window & About Verge). This is not a severe bug though and resize option may be disabled to fix this.
