### ISSUE TITLE
Release 4.0.1 still not working on MacOS pre-Sierra - still need to compile from source

### ISSUE THREAD

**Issue by robbybroon** [vergecurrency/VERGE#475] opened 2018-01-14 12:51 UTC
## Context

The binary 4.0 and 4.0.1 releases for Mac, released as .dmg files do not run on any MacOS version prior to Sierra. This means that many Mac users cannot run Verge-QT, and as Electron-XVG is also broken for all MacOS versions at the moment, there is no wallet solution for Mac users.

I have been able to compile from source and get it running on MacOS 10.11.6 (El Capitan) but i needed to install brew, mysql, ruby, qt, etc. and had lots of version and dependency issues getting it to compile. The instructions in the release do not work for me - I need to do a fair bit more.

Please can the release be complied to work on older MacOS versions, as any Mac older than around 2011 cannot run Sierra, and it has some incompatibilities which means that some users do not want to run Sierra yet. This is a major barrier to Verge being a mainstream coin IMO, the wallet software should work seamlessly.

The official vergecurrency.com site still shows Electrum-XVG as the "official" wallet - and links to the 2.4 build (https://github.com/vergecurrency/electrum-xvg/releases/download/2.4/electrum-xvg-2.4-macosx.dmg) which is broken and fails to start up on all versions of MacOS that I've tried, from Mavericks through El Capitan, Sierra and High Sierra - it's just broken completely.

Providing context helps us come up with a solution that is most useful in the real world -->

## Prerequisites

* [Yes ] Are you running the latest version?

## Your Environment

* Verge Release: 4.0.1
* CPU: Intel Core2Duo 2.2 GHz (Early 2009 Mac Mini)
* GPU: Intel HD Graphics 4000
* RAM: 8GB
* OS:
    - [X] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by robbybroon** [comment] 2018-01-14 15:44
I have made the binary that I complied available via torrent, here:

magnet:?xt=urn:btih:d65341703c691118ca6e460a677eef44d76ecbad&dn=VERGE-Qt.app&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.istole.it%3A80%2Fannounce

**Comment by deliriumv** [comment] 2018-01-14 15:47
@robbybroon No one in their right mind will download that. Your intentions *might* be honourable but who knows?

Why not just post the instructions on how you built it?

**Comment by justinvforvendetta** [comment] 2018-01-14 15:55
that electrum dmg just needs to be dragged into applications. (assuming your user is an admin)

the instruction on how to build the Mac core wallet are in the /docs folder

**Comment by jackito** [comment] 2018-01-14 18:41
The Mac wallet is not user-friendly. You guys still need to hire a UX designer also.

**Comment by robbybroon** [comment] 2018-01-15 08:55
Hi Guys,

It ended up being very complicated to get it to compile. The Mac instructions do not work on El Capitan - I needed to install a bunch of Brew dependencies, and I had a load of things already set up, like git, which the instructions do not mention, but the build fails for example if you just download the zip file directly - I had to git clone it to get the .git file that the build seems to depend on. There were so many attempts and so much trial and error that I don't have a nice set of instructions unfortunately. Searching through my history, I note that I had to:

- brew upgrade ruby
- ran ./configure in the VERGE directory - to get some brew stuff auto-installed - if you don't do this, the build fails
- brew install libevent
- my qt was installed in /usr/local/Cellar/qt\@5.5/ - I had to create a symlink /usr/local/Cellar/qt -> qt@5.5 - not sure why
- brew install git
- I had to manually update my .profile to include qt and git as brew didn't add them automatically to the PATH
- this run: ./building/mac/requirements.sh kept alternately removing qt 5.5.1, then re-installing it - then the next run would remove it, then the next run would re-install it - I tried the build after both a re-install and a remove run, but it failed in both cases - I had to install qt manually and create that sym link, then run the build - if I run requirements.sh it uninstalls qt then installs a version that it doesn't like which causes the build to fail.

So - I thought it was easier to share my binary, as no one seems to be willing to fix this, as I raised the same defect on the 4.0 release - building this from source on an older Mac is not straightforward and not for the layman. Given that I'd expect close to 50% of Mac users can't or are not yet running Sierra or High Sierra - this is a major barrier to Verge adoption:
http://gs.statcounter.com/os-version-market-share/macos/desktop/worldwide

I'd suggest it should be addressed - either get Verge-QT complied on an older MacOS, and it will work on never versions too - or get Electrum-XVG working, and take the broken version off the official site in the mean time.

**Comment by ekryski** [comment] 2018-01-16 05:41
Duplicate of #442.

**Comment by HaberHash** [comment] 2018-01-17 15:10
+1.  Following so I can get notifications when this is fixed.  Hopefully my wallet address doesn't change through all of this.

**Comment by ebrinkster** [comment] 2018-01-28 00:39
Try verge 4.0.1 fork for stealth.  No further issues with macOS for me after this release.

**Closed** 2018-01-29 22:54 UTC
