### ISSUE TITLE
Cosmetic Dropdown Issue MacOs

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#423] opened 2018-01-09 06:27 UTC
<img width="688" alt="screen shot 2018-01-09 at 1 24 50 am" src="https://user-images.githubusercontent.com/35063339/34707535-21e4caa6-f4dc-11e7-8438-34cadf9ec562.png">

Old issue was closed, problem persists in the latest commit.

<img width="183" alt="screen shot 2018-01-09 at 1 26 58 am" src="https://user-images.githubusercontent.com/35063339/34707557-3546bdfc-f4dc-11e7-9eb3-a56765d1519f.png">

Transaction fee also could be improved.

**Comment by justinvforvendetta** [comment] 2018-01-09 06:48
i think this is already open somewhere else

**Comment by Positivism** [comment] 2018-01-09 06:50
Until we find it leave this open.

**Comment by ekryski** [comment] 2018-01-09 20:12
I can reproduce on the latest Tor branch build. 🙁

**Comment by jrsikors** [comment] 2018-03-26 02:53
duplicate of #443  ,, will close this one ... keep an eye updates for #443

**Closed by jrsikors** 2018-03-26 02:53 UTC
Labels: cosmetic issue, duplicate

**Comment by jrsikors** [comment] 2018-04-08 02:46
There had to be some method to my madness at the time ... I was on a roll and got the issues page under 25 from like 65+... until some a-hole started posting a bunch of enhancement requests in the last week :man_shrugging:  :rofl:  :heart:

**Comment by Positivism** [comment] 2018-04-08 02:53
HMMM.

**Comment by Positivism** [comment] 2018-04-08 02:54
Maybe its because you hash-attcked my issue is a duplicate, sending wrong timestamps are we?
