### ISSUE TITLE
-reindex crash

### ISSUE THREAD

**Issue by haydencarlson** [vergecurrency/VERGE#921] opened 2019-05-28 18:35 UTC
# Issue Template

## Context

Trying to run v5.1.1 and v5.1.2 with -reindex causes a crash

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [X] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

Running Ubuntu 18.04
GCC 7.3
Boost 1.65.1

## Expected Behavior

Should wipe chainstate and block index and rebuild both. 

## Steps to Reproduce (for bugs)
Error
```
2019-05-28T19:02:22Z Reindexing block file blk00000.dat...

============================================================ T= 1559070142
Tor 0.3.5.8 (git-5030edfb534245ed) died: Caught signal 11
./verged(+0x5a65d9)[0x56261556f5d9]
./verged(+0x140f58)[0x562615109f58]
./verged(+0x140f58)[0x562615109f58]
./verged(+0x1dd156)[0x5626151a6156]
./verged(+0x1e7bd8)[0x5626151b0bd8]
./verged(+0x1fdfec)[0x5626151c6fec]
./verged(+0x5fe2a)[0x562615028e2a]
./verged(+0x803f4)[0x5626150493f4]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1(+0x11bcd)[0x7f6da7a0cbcd]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f6da5f4b6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f6da5c7488f]
```
*Steps :
1. Try Ubuntu 18.04 ( have not tested on any other distro)
2. Run verged -reindex

## Your Environment

* Verge Release:
* CPU: 8 Core
* GPU: GTX 980ti
* RAM: 16GB DDR3
* OS:
    - [ ] I'm using Mac
    - [x] I'm using Linux
    - [ ] I'm using Mac

**Comment by cod3gen** [comment] 2019-05-28 19:01
What does your debug.log say?

**Comment by haydencarlson** [comment] 2019-05-28 19:02
Oops forgot to include that.

```
Tor 0.3.5.8 (git-5030edfb534245ed) died: Caught signal 11
./verged(+0x5a65d9)[0x56261556f5d9]
./verged(+0x140f58)[0x562615109f58]
./verged(+0x140f58)[0x562615109f58]
./verged(+0x1dd156)[0x5626151a6156]
./verged(+0x1e7bd8)[0x5626151b0bd8]
./verged(+0x1fdfec)[0x5626151c6fec]
./verged(+0x5fe2a)[0x562615028e2a]
./verged(+0x803f4)[0x5626150493f4]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1(+0x11bcd)[0x7f6da7a0cbcd]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f6da5f4b6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f6da5c7488f]
```

**Comment by haydencarlson** [comment] 2019-05-28 19:32
Tried with v5.1.2, same result.

**Comment by justinvforvendetta** [comment] 2019-05-28 22:50
strange, a boost and tor crash... and what happens without reindex flag?

**Comment by haydencarlson** [comment] 2019-05-28 22:54
Runs fine without reindex

**Comment by marpme** [comment] 2019-05-29 08:07
Self compiled or pre-compiled binary?

**Comment by haydencarlson** [comment] 2019-05-29 15:59
Self compiled

**Comment by justinvforvendetta** [comment] 2019-05-29 16:00
@haydencarlson what version of boost did you compile with, and what dist are you using? 

thanks

**Comment by haydencarlson** [comment] 2019-05-29 16:03
Ubuntu 18.04
GCC 7.3
Boost 1.65.1

**Comment by justinvforvendetta** [comment] 2019-05-29 16:52
hmm i cant reproduce this. i have a fully synced node, i closed it, ran ./verged -reindex 

and then ./verge-cli getinfo

seems to be completely reindexing from the beginning.

**Comment by justinvforvendetta** [comment] 2019-05-29 16:52
same distribution and boost version, btw

**Comment by haydencarlson** [comment] 2019-05-29 18:10
Ok so I recompiled v.5.1.2
Downloaded data from https://verge-blockchain.com/
And tryed to run ./verged -reindex I'm getting a different error.
`LoadExternalBlockFile: Deserialize or I/O error - Read attempted past buffer limit: iostream error`

**Comment by justinvforvendetta** [comment] 2019-05-29 18:29
i was able to reproduce that. let me look around...

**Comment by haydencarlson** [comment] 2019-05-29 19:00
Yeah trying to replicate the tor and boost errors again but I'm not able to...
i think that was a separate issue though

**Comment by justinvforvendetta** [comment] 2019-05-29 20:29
i know tor probably has issues with some variants of openssl 1.1.1, but i was not able to recreate the issue with boost you first opened this ticket for. however, i was able to reproduce the iostream error from loadexternalblockfile, so i am working on that right now

**Comment by haydencarlson** [comment] 2019-05-29 20:42
okay so I tried a fresh sync and try to -reindex before it fully synced, and that causes the crash which the issue was originally posted for.

**Comment by justinvforvendetta** [comment] 2019-05-29 22:31
ok i think i may have solved the iostream issue, and now i am able to recreate the original issue you posted. ill continue to leave this open while i explore it.

**Comment by justinvforvendetta** [comment] 2019-05-30 03:31
so "LoadExternalBlockFile: Deserialize or I/O error - Read attempted past buffer limit: iostream error" 

that bug seems to be gone. still working on the reindex crash bug. so far the only solution ive found is to just wipe the blockchain data and restart it, either empty or with the download. there is no reason for me to reindex but its still something we need to get working properly

**Comment by haydencarlson** [comment] 2019-05-30 04:33
ok nice.
i'm working on a branch with address indexing and needed to test reindex
thanks

**Comment by cod3gen** [comment] 2019-05-31 19:26
Got a simliar error too when trying to reindex;

```
2019-05-31T19:23:34Z  block index              78ms
2019-05-31T19:23:34Z Wiping LevelDB in /root/.VERGE/indexes/txindex
2019-05-31T19:23:34Z Opening LevelDB in /root/.VERGE/indexes/txindex
2019-05-31T19:23:34Z Opened LevelDB successfully
2019-05-31T19:23:34Z Using obfuscation key for /root/.VERGE/indexes/txindex: 0000000000000000
2019-05-31T19:23:34Z init message: Loading wallet...
2019-05-31T19:23:34Z txindex thread start
2019-05-31T19:23:34Z txindex is enabled
2019-05-31T19:23:34Z txindex thread exit
2019-05-31T19:23:34Z nFileVersion = 5010200
2019-05-31T19:23:34Z Keys: 2025 plaintext, 0 encrypted, 2025 w/ metadata, 2025 total. Unknown wallet records: 1
2019-05-31T19:23:34Z  wallet                   21ms
2019-05-31T19:23:34Z setKeyPool.size() = 2000
2019-05-31T19:23:34Z mapWallet.size() = 54
2019-05-31T19:23:34Z mapAddressBook.size() = 2
2019-05-31T19:23:34Z Reindexing block file blk00000.dat...
Segmentation fault (core dumped) 
```

**Comment by justinvforvendetta** [comment] 2019-06-04 19:34
@haydencarlson @cod3gen can you guys try this again now? marp fixed it the other day

**Comment by cod3gen** [comment] 2019-06-04 19:45
And its a success! 🥇 👍

**Closed** 2019-06-05 01:25 UTC
