### ISSUE TITLE
mac wallet hangup

### ISSUE THREAD

**Issue by ChiefCeko** [vergecurrency/VERGE#291] opened 2018-01-03 02:47 UTC
mac 10.13.1

loading window appears, "loading block index...", wheel of death, window disappears, nothing happens. app shows active in dock, need to kill

**Comment by dbtftw** [comment] 2018-01-03 02:54
It takes 5-10 minutest to load currently 

this is a dupe of #192

**Comment by satrya-sabeni** [comment] 2018-01-03 02:58
You just need wait. It really looks like the rainbow ball of death and that it crashed but it didn't.

**Comment by ChiefCeko** [comment] 2018-01-03 03:04
thanks, worked out!

**Comment by techpoy** [comment] 2018-01-03 03:07
@ChiefCeko  Please close this issue.

**Closed** 2018-01-03 03:06 UTC
