### ISSUE TITLE
Bittrex Unconfirmed transaction with Electrum wallet

### ISSUE THREAD

**Issue by johnrockson** [vergecurrency/VERGE#505] opened 2018-01-17 23:39 UTC
Hello, 

Would like your help on this.  
I sent some XVG from my electrum wallet to bittrex, the transaction appears as "pending" or "unconfirmed" in my wallet.  When I check the verge blockchain, the transaction has been confirmed hundreds of time but it has still not appeared in my bittrex wallet or even as a pending deposit. 

Is there a way for me to cancel this transaction? What can I do about this? I'm not a coder. 
Is something wrong with the wallet? 
What happens if this transaction isn't confirmed or deposited into bittrex after a few days?
Will it cancel on its own?

Please help.

---------------------------------------------

UPDATE:  I got my coins back, I think. I just did what @justinvforvendetta said to do.  Close your wallet for a day or 2.  It should come back to it.  I'm still confirming things, but it looks like I got my coins back.  

Also @benammann is very helpful with the new verge qt wallet, seek him out if you still have issues.

**Comment by ryanprovofc** [comment] 2018-01-18 01:15
I'm experiencing the same exact issue.  Trying to transfer my coins from the electrum wallet to bittrex but they appear to be stuck on the blockchain. I've been waiting it out for about 5 days but still no luck.

**Comment by johnrockson** [comment] 2018-01-18 02:36
@justinvforvendetta

**Comment by justinvforvendetta** [comment] 2018-01-18 04:14
was this a stealth or regular tx?

**Comment by justinvforvendetta** [comment] 2018-01-18 04:14
if it isn't confirmed it will wither become confirmed or bounce back after a few days.

**Comment by johnrockson** [comment] 2018-01-18 04:20
It was regular tx sent using electrum wallet 2.4.1 

I see confirmations on the blockchain but its still pending/unconfirmed in electrum wallet. 
Will i lose my coins?  Will it come back to my electrum wallet?

**Comment by johnrockson** [comment] 2018-01-18 04:20
Here is the tx id 

https://verge-blockchain.info/tx/e681a920dbc89e22cfd7faf81004294007a2b300a14404b53236f4898e90180b

**Comment by justinvforvendetta** [comment] 2018-01-18 04:31
@johnrockson if you see it in your electrum wallet and it says unverified, it's fine and spendable.

**Comment by johnrockson** [comment] 2018-01-18 04:35
no it says pending, and the Balance has the amount I sent as  "unconfirmed"  

I sent the amt to Bittrex, but it never arrived there. @justinvforvendetta 

I can't spend or send it again from the wallet.

**Comment by johnrockson** [comment] 2018-01-18 04:37
See image below
![image](https://user-images.githubusercontent.com/35546787/35080999-56fd2bca-fbdf-11e7-9453-1b8063dee049.png)

**Comment by raidburn** [comment] 2018-01-18 04:39
Same issue for me when I sent the xvc to Binance two days ago. I tried to export the public keys and import them into Wraith  importprivkey functions but I'm getting a method not found (code -32601) error. 


https://verge-blockchain.info/tx/1f5b944796980442b590a5133692b45880a344386e526a3529225aeefdf2826b

**Comment by justinvforvendetta** [comment] 2018-01-18 04:41
your transaction is unconfirmed and sitting in the networks mempool. it'll either come back or get processed. we tried to soft fork but not enough pools participated so we're going to hard fork in a week and then all stealth txs will be processed and the pools that weren't contactable, will be left behind. bittrex and binance and the top pools will all be fine. anyone that doesn't participate we will delist.

**Comment by johnrockson** [comment] 2018-01-18 04:43
are you talking to me @justinvforvendetta ? or raidburn?

**Comment by johnrockson** [comment] 2018-01-18 04:46
my tx was a regular transaction using electrum

**Comment by johnrockson** [comment] 2018-01-18 04:47
my transaction is 
https://verge-blockchain.info/tx/e681a920dbc89e22cfd7faf81004294007a2b300a14404b53236f4898e90180b

**Comment by gizmogaurav** [comment] 2018-01-18 20:05
The same exact issue is coming to me. My transaction was pending from 1 week and its still showing as pending . Please let me help whether the transaction will auto cancel or i will loose all my verge coin.
here is the transaction id - 

https://verge-blockchain.info/tx/885ae933a1caad5d36c8fee40981d83de837f9ed77fa018c23c5ac2be9543963

**Comment by johnrockson** [comment] 2018-01-18 20:06
Transaction has confirmations but the BLOCK has zero confirmations.  
Block 1807816

https://verge-blockchain.info/block/000000000000a183412f6666f0c17ab7f07ba494cffc8f6d628c1ec8b88702c1

**Comment by juultje123** [comment] 2018-01-19 09:50
Guys please be patient, nobody will lose their Verge. They will have to do it the "hard" way because pools did not participate (I don't know why). But nothing is lost, just takes some time.

**Comment by NB3025** [comment] 2018-01-19 10:09
How long does a hard fork take?

**Comment by johnrockson** [comment] 2018-01-19 20:14
UPDATE:  I got my coins back, I think. I just did what @justinvforvendetta said to do.  Close your wallet for a day or 2.  It should come back to it.  I'm still confirming things, but it looks like I got my coins back.  

Also @benammann is very helpful with the new verge qt wallet, seek him out if you still have issues.

**Comment by Zeeko22** [comment] 2018-01-20 01:31
I have seen on bitrrex the wallet says offline!!!! 

its not fault on bittrex aswell?

**Comment by gummideepak** [comment] 2018-01-20 14:01
@johnrockson Feel free to close the issue! 😃

**Comment by gizmogaurav** [comment] 2018-01-21 04:39
Update: Got my coins back and transaction which has 0 confirmation got cancelled. Now i again try the transfer to bitttrex from wallet and it got successful.

**Comment by gummideepak** [comment] 2018-01-21 05:48
@justinvforvendetta You can close this issue as it is solved!

**Closed** 2018-01-21 20:07 UTC
