### ISSUE TITLE
Encrypt wallet: no decrypt possible windows QT 4.0

### ISSUE THREAD

**Issue by themaxx2k** [vergecurrency/VERGE#220] opened 2018-01-01 18:33 UTC
Hi.
After encrypting the wallet it is not possible to unlock the wallet. Tested with some special chars, and also only just with lowercase. This is urgent, people müwill loose their funds when they can not access them due tot his issue. OS win7 64bit

**Comment by themaxx2k** [comment] 2018-01-01 18:40
Weird. When changing password the encryption password is accepted, but not for unlocking the wallet. Will test once more with changed password

**Comment by justinvforvendetta** [comment] 2018-01-01 18:42
what about thru the console?

**Comment by themaxx2k** [comment] 2018-01-01 18:45
Will test, give me 5 mins. Startup takes long... will report on github. Btw. Thanks for your hard work. Best wishes for you, your family and the whole team. Nice to see the dev is in contact with their users. 

Gesendet mit der GMX iPhone App

Am 01.01.18 um 19:42 schrieb sunerok

**Comment by themaxx2k** [comment] 2018-01-01 18:55
Ok will verify once more but it seems that the wallet gets unlocked even while it reports wrong password. What command for console do i have to use? Walletpassphrase? What does walletlock do? (Does currently nothing...) wallet stay open. 

Gesendet mit der GMX iPhone App

Am 01.01.18 um 19:42 schrieb sunerok

**Comment by Himan2001** [comment] 2018-01-01 19:01
@justinvforvendetta 

Plase take a look to the 3 open tickets because of the wallet/lock/unlock problems.
It is only working in QT via the menu. the daemon is no longer working.

**Comment by themaxx2k** [comment] 2018-01-01 19:02
It reports wrong password, but unlocks wallet...

Gesendet mit der GMX iPhone App

Am 01.01.18 um 19:42 schrieb sunerok

**Comment by Himan2001** [comment] 2018-01-01 19:14
It does not unlock in daemon. when wallet is really unlocked you can see with "getinfo" how long the wallet is unlocked. As long here is -1 or 0 - you can not solo mine and use shell scripts for tx.

At the moment the only quickfix is to create a UNENCRYPTED wallet and work with them until the problem is completly fixed :(

**Comment by olanate** [comment] 2018-01-01 19:16
I changed password... then unlocked and now it works. On Windows10.

**Comment by justinvforvendetta** [comment] 2018-01-01 19:49
hmm ok at least we are getting somewhere now...

**Comment by MoonChild1234** [comment] 2018-01-01 20:30
wouldn't it have been better to test your code before tweeting that it will be done before end of the year and then get upset when people keep asking? in all seriousness, why are you doing this to the very people that support you?

**Comment by LKfighter** [comment] 2018-01-01 21:55
Check #238 > it is the same issue except the coins are sent after the false incorrect password notification.

**Comment by Crunklin** [comment] 2018-01-02 16:09
Can confirm after changing password wallet unlocks properly and when unlocked does not prompt for PW when creating address and sending.

**Comment by Hectormang** [comment] 2018-01-03 05:37
The unlock error message issue in QT 4.0 is still present even after changing password.
OS Windows 10 x64.
- Error when unlocking password regardless if correct password is used or not.
- Even though error messages says password is incorrect, wallet icon reports as unlocked when correct password used.
- Cannot lock wallet after unlocked
- Error message when trying to change password, says original password is incorrect. It is correct.
Haven't tried sending coins. Want to ensure security before transferring balance in.

**Comment by Arjenmk** [comment] 2018-01-04 12:25
Tested it on windows 10 machine.
- Encrypt seems to go fine
- After restart wallet and clicking unencrypt and entering password error message says password incorrect
- Clicking cancel shows wallet icon as unlocked.
- When going to console and typing walletlock noting seems to happen and wallet stays unlocked or at least so it seems when clicking on lock icon.
- Completely removing the verge-qt app (including appdata/roaming/Verge folder and installing app again and putting a backup of the wallet back in place also does not change the behavior (unlock still gives error but wallet seems unlocked)

**Comment by jrsikors** [comment] 2018-01-25 19:17
Please check again with the latest wallet 4.0.1 for stealth transactions.  I believe all the wallet lock / unlock / decrypt functions now work.

**Comment by Influence2** [comment] 2018-01-31 22:06
@themaxx2k This issue should have been resolved in 4.0.1 wallet. Can you confirm and close the issue if so?

**Comment by Hectormang** [comment] 2018-01-31 22:09
I can confirm fixed on my wallet. Good job!

**Comment by Hectormang** [comment] 2018-01-31 22:11
I didn’t open the thread. I don’t think I can close it.
Or was this a group email?

**Comment by Influence2** [comment] 2018-01-31 22:16
@justinvforvendetta @Max-Meldrum Does #500 fix this issue, and allow it to be closed? No updated from OP for weeks.

**Comment by Max-Meldrum** [comment] 2018-01-31 22:24
@Influence2  I know the lock/unlock issue is solved but not sure about the thing with people's passwords not being accepted. But as you said, as no response from OP in weeks. I don't have permissions to close the issue, hopefully Justin sees the convo and takes action hehe.

**Comment by justinvforvendetta** [comment] 2018-01-31 23:37
I seent it!

**Closed by justinvforvendetta** 2018-01-31 23:37 UTC
