### ISSUE TITLE
Transaction sends but gets stuck in mempool

### ISSUE THREAD

**Issue by SwenVanZanten** [vergecurrency/VERGE#853] opened 2019-01-26 13:20 UTC
# Issue Template

## Context

I have a transaction which was created via the iOS wallet and got stuck in the mempool.
I've tried sending the raw tx which v5.0 and it gets send but still ends up stuck in the mempool.
When sending the same transaction with a v4.0 codebase it rejects the tx before sending it.

The debug.log error for v4.0 is:

```
ERROR: FetchInputs() : 75874fa8c8 mempool Tx prev not found a9cdcb0897
```
https://github.com/vergecurrency/VERGE/blob/9d0cd61f8d2a45a90cba5a2ad4d0167f4b85d240/src/main.cpp#L1430

The console command `sendrawtransaction` stops here:
https://github.com/vergecurrency/VERGE/blob/9d0cd61f8d2a45a90cba5a2ad4d0167f4b85d240/src/rpcrawtransaction.cpp#L525

The raw transactions:
```
010000006a044a5c1ade6eb9b29224dc6147369161102285c0df65c91916f1ad9b4883a89708cbcda9010000006b483045022100eac3da4050f324083119bc32e594e0d9ba5e055f30501b801b15ad32fbb9c109022030a1bf8fee8c692cbfd5785d507a4df1ed5c64feee755793d7dfdebf23c3ea6d012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff34741a34a9a8e7bb562193f74af250acec6723ea006449d5cbe1f8e069597806000000006b483045022100a53820d4dfe12a2355a980112ec0341908c5272a4c7ece11203dd0ce63a738c402207936ce236bc3831fc2ac0c38a4c6380d10768b0f6d93c002bf0b510b389a354b01210286dd4f43e9f5845c2da6a88ec568fb8745cbbed1d7c7d98e0bb20c23c087e31bffffffff37ace8b330afd34287ec1f1ba03109ac93be265e74eccdf025f3f5b17e7213fb000000006a473044022009de4f1bc99806f333fcc9fa7bc40fc3fb70a4b12c989008210c63e54f88a1a50220703479faa99571106a88649236e929390f087774a26bc8ef5aa6021c8b43f635012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff835d38324ffc76855c42c87ddfef175837af1f2667e30fee88a3b58d0f6af68d010000006a47304402200647b7cb7439f36d8abefb78194a41eea1926c3c76151dc00f3d689b8f034a2a0220197f9faac69517b3f74c23374012fc621d111d40b719f2fc50c32642f9e9026f012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff1e4c6019bacaf9ab9313d0dd871220112b40517b02c794523def4832f5c5c9a8010000006b483045022100969f797c7b61558df29b8ae9eca49143e4f839d54fc57b0511a9c6ff6914bd4302207956308b5487dd70ca602f66feabe1d4d5e6d2b1f353524e21423b3a667f7e72012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff1b1000f1203483dfc0d796bcc7ad8a0bf504711f03e54daa8df2679067592664020000006b483045022100bfdd20627a91d92ed588af54ecb096f7ffef4a65ad6ba22a17bcf5ef41b0ab4402204de9b216336799a5ed59498c83b8e809601eabab22140c92e111430c8fef44c2012102185d9636a12b1680a642bb7f37e7a463bc2ff77d48f52a87614ac240e84cec8effffffffb532dda3f6feaedd33344f209d77af320cfe432213249595777857c700393ec4010000006b48304502210098b7a3f5e3622403eff0e29f0768811534d7d2ddbd743d85689f5b0f653c62e50220641aea8d81b13d8ddb4d66073abbe1db1afafee314247f13d6f64a466b7ab1120121024c32eac745707e4c01ca8f431eea5119f830d2add5c67521241935e8e362c64cffffffff88c3c8f9c658931fd19fa8d46d91201e47c17c47b505a6a3de5d505d6217543f010000006b483045022100bccf46e34102828af8200f596bb92dec3aa8b03afee19997b0111adf552001dc0220348b79468038c396e34ec19256b78d7e5d03009c531f9b8b6a0eecec49a53877012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff4cb89267da52f6a385898978240f2034568514259d60d3854d95d47812c02fed000000006a47304402200eaffb9a100a5a147c39437908f26376308c83f80be4d19bcf5e312a6f70e73402201e7a0cc234f98459abb6c60d0c8a4cdb9625ce4c64c97a685370616e2619a354012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff546b90cc4f945a5ae4f93de62c6e65489012a6f846c184fbdc7cbc40ec3c4ed6000000006b483045022100a49c3ed240472d92b8d0d9d22c2a67aa08242ff6fec53b2c2e086a0c3bfe5d940220731ff1c3768e53ee590c640f0956de55959d80f161ba58fbc7c7b7e6d7e0f1a2012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff3117546421a53ab13ad492107456fa1eacdb7010c5eea675aff6fee3f7820e89000000006b483045022100dbbab2e5e1813c1711d4b6bae2fc9b95596e98bf403d7ac7d9a8d44e832d901d0220750d6483eb1acab35fa8b22375b5dc3cf42b2bec7a7b14d43b995b7effd95953012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff1421282558833f391c88403c2679b460324e8c88c8c3a0fb7f9e559f5efa8f21000000006a47304402203fade24efede6296e5ef0fa34f4ba4ad629aac2cdf0bc438fd847319dd127e9e022049c2120d71b64fc86d4b878eff015a24848dddfd42d93752f5d9c687eafc2c83012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff1113d59995adaeef0fa418f9811a969204b7d5e461a2108a2d722e2278092531010000006a4730440220085f45a9421a4a73da12ffea788efef822909a46aea1413b45ecaa6e1d742acf02200fa1b3e455cd58b4caea47a221d2ce7253b9dfc3cd22ec39d3c99096531f7c76012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffffba8f5739902c514d19aa24df925228a2e99568d565236bc3422d249287b69c8b000000006a4730440220764f53893741fea21c4f5b855676383e0e8c028dc9668566e16dd5edc68291e002203f70daa8a0f8fd9f7710cde25c51843cc78b63534ea3de6fb91fbe036d1ecec2012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08efffffffffa7e33409da17f26699defbba5f0f4acff82e7288da05d731416f72ed18f6966010000006a473044022075e9f5526782348fbb58516b9bb0f68b8572260ee8540b0e68edc86592a29ffd02202668dc49070c9e5408de159a11952ffab185bc49061dfd7002517d8922d1586a012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffffa4cae7abfbc4ef3d3bd1f717316a02a02626e6897fc8960b38188179b3a4b239010000006b483045022100dfb6db2145b9938af1eb6e6aca4d40af8e3605efac914fcf64642bb7fac0c50d02203cbbe087fee6dac4473561be624244ce47ed749987cf7979638c4cea983bd416012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff6dbeee68fa96ebbbd84e70571fcccbf42b97c05b4e31bba9867af16b76d03c7a000000006a473044022047e8aeea180212f7a48c108a8af38f684f20b72dcfe83a1be1ab973fb9853377022071340961a1a2e9c716e0cc85d7cc62b74a648914ac95d928fe6eb73200c6ed130121025ac0875cb09c5e38abb676a4ad3de95ef071eede12c3c1c74c2e2f2d1bab62beffffffffdc3bf69ec5e5083038a5f21a514917174d0d20e11e39294281d549078868a065000000006a4730440220705d5fb89c687cf3c316ac0830c5e4d68fc68fcde87224a9aae1caf496382cf902203431b6a1a0aaa39f874ebe56b4a234a75c94d24b7019e42a93674f349f7ae105012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffffa2baa096463b891e7e6c982a3b5443a4e7f55b1ffb0512e68e24bea08400116d010000006b483045022100818a37f9942b8d23d1fdcb3781270fac763420a163daa70f5c611c3f555fa3db02202006c0c1209b1d6d2dd531fe0a6f410dfc1ef3b075cfbb19deef53ac39e54789012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff5cb451af683030b7980fd36a2c53f552690a2720e92d6f51fac2b3fa1b76f84c010000006a47304402200f35f5fa4cd5749a9586662ea252273e1f33fbc810d3b96349003dc31b9f668802206ccddd3d354f909d365ca16fa8d4ca97cf499cd1008dd3faf5db7cf85b4f8f22012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffffd4baabfe329d81cf3df63e3aba317d7995e73152deac48990faa7dee940bbff5010000006b483045022100de5fb6a571835879e1d97aecd9eb330be68b0d0492eb181a57ec08643b5e9d150220281c97526f5742365b8daa4d8a7ed9e87bee732fe8ca349203568f63c9c450e4012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff45106a0483b38270a712f0c3f602e072ae2f1d1f34f4b93fa843c5e2f7e47f44000000006b483045022100bd828dca8472d57e9a008e634d8dc98062df3485d843d8f7712b18f6a8e55fc9022077fe7eca9d11c020d8dfef201ae7e5e92df2a42bb19f5fa21a2f8a1e1867f0b8012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff73ce1430af6a594ee2652e7bcf7288453462085b48ee64f38d43e2d55a304c13000000006b4830450221008f61926d72dbd5b8868e2c4f867ec785a7a7cd0e0adff7a8bc8ef00ceb93c74802201c0597ced72f1d33268ef4bcb1e07992e01195106891f8f8aa88a6a1e8c7ba5e0121037d654a97cc80ec21b43edfd00ef89467e5b9fc115fd623389c5ac5b2a5078c3cffffffff7abc9088dde239a749c68996f1e42634e59482379974b7d5473c9d6cae0f0374010000006a473044022036c75fa9eef7b6e89c6328799c6b79512f9963284b0d35f8f7bc485c6ea3479902204c216d9207f22afa10cd3461d973ca38f3ecc281cd67ebd9c4b1a4d3882b8a1f012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff2ec35b070716528faa76ec720dacbbfaecb0f7c6b51ee488bb3a1bfeb008d467010000006b483045022100d3d34388862729e87e58d28c92a73794d31bcade6232f66092408d96a3a830050220330654a031794604f015df2aa253a4083ecd853a48100db3e08b6b2aa77417e1012102006e12fda8f30e4322263610ae240cb1c5ecb05839730a573cd78d910fb9e08effffffff8af39dff9aa4151f89fc54bc7e58ba08bdcdf05e8e4a7fb5bb6b1020c14e9423010000006b483045022100eca10851ad94bf659307fda3cf128539f7ce71121d19502aa5d249977f7bb32402203d7e24293bd763b9ccaeba42f75639d8f6a12888a2e170abf74eb7c2654256640121037ee5082d48dad42517622345019e45e5d833ddcf822af3a876fae0f9dea24370ffffffff01188dfeb0000000001976a914891b4209a7ae917a1e61a5984874daa99127549688ac00000000
```

**Comment by bmhjyu** [comment] 2019-05-29 13:54
From what I can see the minimal fees required for a transaction in 4.0 and 5.0 are different. In 4.0 we can see the following codes.

https://github.com/vergecurrency/VERGE/blob/9d0cd61f8d2a45a90cba5a2ad4d0167f4b85d240/src/main.cpp#L614-L616

While in 5.0 the following codes are used.

https://github.com/vergecurrency/VERGE/blob/8e663893d96cf8352be8dcc89895ec9efdc9b87d/src/wallet/fees.cpp#L18-L26

This means in 5.0 will have lower minimal fees required, if transaction is larger than 1000 bytes.

**Comment by kusatz** [comment] 2019-06-12 07:51
i also have transactions stuck in memorypool?? (since june 2nd)
<img width="1023" alt="Screenshot 2019-06-12 at 09 49 33" src="https://user-images.githubusercontent.com/51738809/59332868-881e2b00-8cf7-11e9-969f-d09d7d3b84fd.png">

no idea what to do??
 #help wanted

**Comment by SwenVanZanten** [comment] 2019-06-12 08:26
> i also have transactions stuck in memorypool?? (since june 2nd)
> <img alt="Screenshot 2019-06-12 at 09 49 33" width="1023" src="https://user-images.githubusercontent.com/51738809/59332868-881e2b00-8cf7-11e9-969f-d09d7d3b84fd.png">
> 
> no idea what to do??
> #help wanted

He,
You could try this:

* Export your private key 
* Delete wallet.dat file
* Open wallet with zero balance and already synched
* Import the private key
* Fire the `rescanblockchain` call from the console and wait until its done.

With the next transaction you try to create small transactions, to prevent them getting stuck.
Until this bug is fixed.

**Comment by kusatz** [comment] 2019-06-12 19:26
thank you a lot 👏

**Comment by tpfuemp** [comment] 2019-06-25 08:42
is this correct, that the fee calculation is disabled and set constant to 0.1 XVG ?
[https://github.com/vergecurrency/VERGE/blob/603654beef9b60823d0aa30481de25448a0c5e43/src/policy/feerate.cpp#L26
](url)

**Comment by marpme** [comment] 2019-06-25 14:55
I’ve opened a branch this morning, working on a fee fix
https://github.com/vergecurrency/VERGE/tree/bugfix-fees-structure

As our feerate isn’t Variable it doesn’t make sense to keep those files anyways 
But for now I will keep it simple

**Comment by tpfuemp** [comment] 2019-06-25 20:48
this fix is only on tx create not relay check, so i have dead transactions in mempool of v5 nodes, which will not accepted from v4 nodes. so this transactions will never get written on blockchain by v4 mining nodes.

**Comment by marpme** [comment] 2019-06-26 06:19
@tpfuemp sure, but you have to manually abandon the transaction. It will not automatically remove your tx from the mempool just by too low fees

**Comment by tpfuemp** [comment] 2019-06-26 07:48
this won't help. after erasing mempool the malicious transactions will be rebroadcasted after some minutes from other v5 nodes. As I understand the code right the fee is checked against fix value (0.1), regardless of transactionsize. 

to be clear - I won't bother you with useless tasks. my intention is to find differences on network level between v4 and v5 nodes to get v5 nodes working for mining. as @pinpins mentioned on other thread, v4 has reached "end of life" for mining, so we should get v5 compatible working.

**Comment by marpme** [comment] 2019-06-27 06:18
@tpfuemp Surely true there. I feel the same way but we are also making some steps towards this goal and I don't think this is useless. I think we should rather "forbid" too low fees you basically can't send a tx with a fee below what you described (0.1 XVG/KB)

**Comment by Woutoud** [comment] 2019-06-27 19:36
> 
> 
> > i also have transactions stuck in memorypool?? (since june 2nd)
> > <img alt="Screenshot 2019-06-12 at 09 49 33" width="1023" src="https://user-images.githubusercontent.com/51738809/59332868-881e2b00-8cf7-11e9-969f-d09d7d3b84fd.png">
> > no idea what to do??
> > #help wanted
> 
> He,
> You could try this:
> 
>     * Export your private key
> 
>     * Delete wallet.dat file (backup first!!!!)
> 
>     * Open wallet with zero balance and already synched
> 
>     * Import the private key
> 
>     * Fire the `rescanblockchain` call from the console and wait until its done.
> 
> 
> With the next transaction you try to create small transactions, to prevent them getting stuck.
> Until this bug is fixed.

So I should export every private key that holds XVG that is stuck and re-import them in this manner?

**Comment by marpme** [comment] 2019-06-27 19:39
> So I should export every private key that holds XVG that is stuck and re-import them in this manner?

Exactly, you could also try the "abandon" transaction functionality, but that only works if it is in mempool only :)

**Comment by Woutoud** [comment] 2019-06-27 19:47
Okay, I'm super new to this stuff... Any hint as to where to find how this works?
I can't find it in the command-line options...

**Comment by jrsikors** [comment] 2019-06-28 03:30
unlock your wallet first.. either through the UI .  Then go to Help -> debug window -> console

to export private key it's:
dumpprivkey "address"

so like:
dumpprivkey "Daslkdjas9321481" , or whatever address it is you have your coins on.

Before you do the next step, make sure that's the only address in your wallet that has coins.  If you have 50,000 coins on that address, go to:
https://verge-blockchain.info/
search for your address, and make sure it really shows 50,000.  If it doesn't, your coins are likely on other addresses

So copy the result of your dumpprivkey to a notepad... keep very safe and secure.  This is the key to your wallet and doesn't require a password/passphrase.

Close down the QT wallet.  Go to your DataDirectory.  Most likely in C:\Users\YOU\AppData\Roaming\Verge

make a backup of your wallet.dat (copy it to a jump drive)... and then rename it to like "wallet_old.dat"

open up QT wallet again

back to help -> debug -> console 

now do:
importprivkey "address"

Should take a few minutes.

Now your mempool should be clean.. and proceed with smaller transactions

**Comment by marpme** [comment] 2019-06-29 18:12
The fee problem is fixed with #948

**Comment by EMO18** [comment] 2019-06-30 05:49
Anyone had a play with TX size?  What is the most you can send without it getting stuck?

**Comment by marpme** [comment] 2019-06-30 09:29
Well with the latest master you will be able to send any tx size without being stuck. 
For now, there's a certain area where this happens. 1000 bytes - 1024 bytes etc ...

**Closed** 2019-07-03 06:21 UTC
Labels: bug, help wanted

**Comment by 0xeD2B34e8cDb8CC913A6fe793AcC7eEE6cE6Fe** [comment] 2019-07-04 05:58
Hello Marpme, despite the issue being closed about 23 hours ago, I do have 2 questions which are directly related to this issue: 

1) How does one ensure that transactions "stuck" in mempool (because size too large > 1kb) since June 30th (4 days) go through at this point? I seem to misunderstand what an updated master means; i.e. does the master affect the VergeLumos 5.2.0.0 wallet (must we download a new version of the wallet?)

2) Transactions which are "Status: 0/unconfirmed, in memory pool" which are not eligible for cmd abandontransaction, will stay stuck for how long? And is there another way of getting these unstuck?

Also I meant to talk to you about something else: I understand that very little people are currently working on this project and I can only imagine the level of fatigue and strain, as such, I sympathize with you guys, nonetheless, this is one of the most complicated and counter-intuitive platforms (my humble opinion). As a miner, having to wrap my head around the concept that one must bundle transactions together before being able to transact was not easily found nor explained - I have mined using ASIC and GPU several currencies and this is a first for me - and the lack of info to boot is a bit much. The inability to increase the transaction fee despite it being an option in the wallet is baffling at best; But what really makes things worst is I have seen comments and responses from a member of your team which tbh are somewhat curt as the onerous of knowledge seems to be put on us the users. The users cannot make any assumptions as to the fitness of what is put forward by your team and trust in basic functionality based on the expectation of the average user is legitimate - when these people express their concerns, in my humble opinion, these should not be ridiculed of dissed just because they are not up to your teammates standards of technical intellect - these are your customers, backers, believers and some of them have vested interests in your work and support to be able to access their funds (THEIR MONEY). So may I suggest that a particular member of your team (I think you may know who I am referring to) keep this in mind next time he/she feels that the pesky customers are bothersome and more-or-less tells them to piss off. Verge was once a project full of promise of a bright future and those who have stuck with the project despite several incidences such as the "hacking" of the mining algo and the drama concerning that the core code is allegedly a copy paste of another project, deserve a little respect IMO.

If I got any part of this incorrect, please forgive me.

Peace my friend 

0xed

**Comment by marpme** [comment] 2019-07-04 06:54
Wait for the new release and download it, afterwards everything will be 👌
It's not like that I can time-travel and implement everything at once, but we are working on rejected "too low fee" tx's. 

I assume that you might be using new functionality too, but obviously they won't work now, as 99% of the network is still dominated by v4's and they will reject everything unknown or new to them. So you always have the opportunity to just rollback to v4 - always keep that in mind :)

**Comment by 0xeD2B34e8cDb8CC913A6fe793AcC7eEE6cE6Fe** [comment] 2019-07-04 14:40
Thanks Marpe, I do appreciate the info - however, in what time-frame 
![Screenshot](https://user-images.githubusercontent.com/52521125/60674420-5e0fe280-9e37-11e9-972b-335138741b3b.png)
do the "stuck in mempool" transactions get released/reverted?

**Comment by jrsikors** [comment] 2019-07-04 14:53
If you want to clear them, you can check out my instructions here:
https://github.com/vergecurrency/VERGE/issues/853#issuecomment-506586680

Basically it involves exporting your address private key, creating a new wallet.dat (make sure you create a backup and passphrase on it) , and then importing private key again.

**Comment by jrsikors** [comment] 2019-07-04 14:57
and just out of curiosity -- has your wallet been opened and running constantly since 6/30?  I remember reading somewhere that they will eventually time out, but that process only takes a couple days (your wallet needs to be open the whole time).  

So if your wallet has been running since those 6/30 transactions, and they are still stuck, I think you might need to follow those instructions to clear them out.

**Comment by jrsikors** [comment] 2019-07-04 15:03
and have you tried to right click the transaction and select "Abandon transaction" ?  If that option isn't available, then your only route is to do the export/new wallet/import I believe.

**Comment by tpfuemp** [comment] 2019-07-04 15:29
you can also try to delete mempool.dat - file and start Verge-wallet with option -zapwallettxes

**Comment by marpme** [comment] 2019-07-04 15:57
We should actually also reject low fee txs inside the mempool, that won’t solve the problem of broken txs in your wallet as you can create them anyways (somehow)
