### ISSUE TITLE
Wallet synchronized but, does not show my funds

### ISSUE THREAD

**Issue by cryptojonnyboy** [vergecurrency/VERGE#604] opened 2018-02-06 01:43 UTC
# Issue Template

## Context

Hello everyone,
I made this transaction to my Verge Wallet the 4.01 version the latest one. For some reason I can not see the balance reflecting on my Verge Wallet even after I made the wallet syncronized am I doing something wrong?

https://verge-blockchain.info/address/DEsVt3iLCXWv8cr2eDZbUwpnhfSu7LR3Lx
What can I do to solve this problem?
## Prerequisites

* [x] Are you running the latest version?
YES
## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [V ] I'm using Windows

**Comment by jrsikors** [comment] 2018-02-06 02:18
Help -> Debug Window ... please post a screenshot or details pertaining to your version ... current block ... max block.. etc.

**Comment by cryptojonnyboy** [comment] 2018-02-06 02:31
Thank you for commenting
![verge](https://user-images.githubusercontent.com/35565338/35838953-3468a45e-0aee-11e8-913a-5307cae01cbc.JPG)

**Comment by jrsikors** [comment] 2018-02-06 02:39
Your last transaction occurred on block 1,857,209 ... you don't seem to be fully sync'd yet... at least not to that level.. I would wait a while longer.

Try closing out of Verge and re-open it just to make sure it's really syncing

**Comment by cryptojonnyboy** [comment] 2018-02-06 02:49
Thank you for your commend @jrsikors 
Yes I figured that out, but the crazy thing is that I reopen the wallet almost 10 times and it said that I was sync but I saw now transaction And also sync with the current block.

**Comment by jrsikors** [comment] 2018-02-06 02:55
After you open the wallet -- sometimes it takes about 5-10 minutes before the 'sync progress' bar shows up.  So just be patient and you should be good !

**Comment by jrsikors** [comment] 2018-02-06 03:07
If you think it's stuck -- you can always try deleting your <datadir>  (NOT YOUR WALLET.DAT !) , download the blockchain in zip:

https://verge-blockchain.com/howto

https://verge-blockchain.com/down

**Comment by jrsikors** [comment] 2018-02-06 15:14
Are you good now or still having problems?

**Comment by cryptojonnyboy** [comment] 2018-02-06 16:46
Hello @jrsikors, Thanks for you help. For some reason I needed to download the blockchain again. It seems that it gets stuck for some reason. So downloading it helped me out. I have one question maybe you could help me out with it. How can I get the private keys of my wallets I used the following command on the console:

listreceivedbyaddress
dumpprivkey
As a result I get the following message:

Wallet is unlocked for minting only. (code -13)
So How can I get the private keys?

**Comment by jrsikors** [comment] 2018-02-06 17:00
**Lock** your wallet through the UI...

now go to the console...
if your passphrase is "cryptojonnyboy" , then type:
**_walletpassphrase "cryptojonnyboy" 300_**

This will unlock your wallet for 300 seconds.

Then you should be able to dumpprivkey

**Comment by jrsikors** [comment] 2018-02-06 17:03
I'm not sure if its a bug or working as intended (@justinvforvendetta ) , but the 'unlock' through the Wallet UI doesn't do a full unlock on your wallet.

The only way to do a full unlock is to go to console and do a:
**_walletpassphrase "your pass phrase goes here" 300_**

**Comment by Technophant** [comment] 2018-02-06 20:30
@cryptojonnyboy, so the new blockchain allowed you to see your balance?

**Comment by cryptojonnyboy** [comment] 2018-02-06 21:23
@Technophant Im going to try the nextime to do it that way to see what results im going to get. Yes the wallet showed my actual balans, but it took me alof of work to fixed it. Thanks for asking.

**Comment by cryptojonnyboy** [comment] 2018-02-16 19:34
Hello @Technophant and @jrsikors,

Is there anything I can do to get of this ongoing wallet synchronization? Downloaded the blockchain of the 13 th and 14 th. No progress at all its kind of stuck. So do you guys have any ideas I can try?

**Comment by jrsikors** [comment] 2018-02-16 21:15
Really not sure.  Can you post a new screenshot of your debug window like you did before?  And maybe your console in general?

Why do you think it's stuck?

**Comment by jrsikors** [comment] 2018-02-16 21:18
Also -- go to your datadirectory .. default is like c:\users\<you>\appdata\roaming\verge

Is the blkindex001.dat or any of the other .dat's growing in size?

**Comment by cryptojonnyboy** [comment] 2018-02-16 23:38
Not really any  signals of growth in that, dat. file
![verge stuck](https://user-images.githubusercontent.com/35565338/36334009-a0973714-137a-11e8-88a9-4049a8891d43.JPG)

**Comment by jrsikors** [comment] 2018-02-17 00:23
Well you are on the wrong version of Verge now.  You have to be on the latest.  Old wallets won't sync.

Your previous version had version "Funky beta" ... this one is the old "unk beta"

**Comment by cryptojonnyboy** [comment] 2018-02-17 02:36
@jrsikors It seems to work. The Funky beta, I missed that little detail. Thank you!

**Closed** 2018-02-17 03:50 UTC
