### ISSUE TITLE
Address created regardless of incorrect passphrase message when passphrase is correct

### ISSUE THREAD

**Issue by Jyobo** [vergecurrency/VERGE#207] opened 2018-01-01 14:26 UTC
Create new address with encryption enabled 

Enter correct passphrase

"The passphrase entered for wallet decryption was incorrect"

press ok , cancel, then address is still created?

Not sure if safe to send coins to these addresses?

<img width="971" alt="screen shot 2018-01-01 at 14 08 03" src="https://user-images.githubusercontent.com/2152836/34468381-a09c99a6-eeff-11e7-8ed0-6d043c293115.png">
<img width="1440" alt="screen shot 2018-01-01 at 14 07 50" src="https://user-images.githubusercontent.com/2152836/34468382-a0b493b2-eeff-11e7-972a-25986e67be9e.png">
<img width="972" alt="screen shot 2018-01-01 at 14 07 38" src="https://user-images.githubusercontent.com/2152836/34468383-a154ef2e-eeff-11e7-9cc0-cf2557ead985.png">
<img width="975" alt="screen shot 2018-01-01 at 14 07 30" src="https://user-images.githubusercontent.com/2152836/34468384-a21a1920-eeff-11e7-8c8c-47d5cc8820d4.png">
<img width="971" alt="screen shot 2018-01-01 at 14 07 16" src="https://user-images.githubusercontent.com/2152836/34468385-a2f51dcc-eeff-11e7-9756-640b0dba7eb1.png">

**Comment by Himan2001** [comment] 2018-01-01 14:41
look here:
https://github.com/vergecurrency/VERGE/issues/202

so it looks like there is a bigger issue with the password handling/locking/unlocking.

**Comment by Crunklin** [comment] 2018-01-01 16:15
Also having same exact issue here on Windows release

**Comment by Crunklin** [comment] 2018-01-02 16:13
Try changing password then unlock wallet. Worked for me. No longer prompts for PW when creating address or sending. @Jyobo

**Comment by jrsikors** [comment] 2018-03-26 01:51
should have been resolved in the latest release.  please open a new issue with steps to reproduce / screenshots / etc if still a problem.

**Closed by jrsikors** 2018-03-26 01:51 UTC
