### ISSUE TITLE
New Wallet not mining

### ISSUE THREAD

**Issue by pool2mine** [vergecurrency/VERGE#707] opened 2018-04-12 18:25 UTC
hello, i have set up a small mining pool for verge with about 500Gh on blake2s, i could not get a block on 48 hrs running non stop, looking at my blake2s.log file i found this errors:

18:15:33: XVG 2054281 - diff 13544747.158115184 job 522 to 145/145/145 clients, hash 545540.144/1530901212.545 in 1.3 ms
18:15:55: XVG 2054281 - diff 13544747.158115184 job 523 to 145/145/145 clients, hash 535762.673/1530901212.545 in 1.4 ms
**18:16:15: Verge 2054282 not reporting**
18:16:16: XVG 2054283 - diff 13544747.158115184 job 524 to 145/145/145 clients, hash 528200.539/1572276920.992 in 1.3 ms
18:16:36: Verge 2054283 not reporting
18:16:37: XVG 2054284 - diff 13544747.158115184 job 525 to 146/146/146 clients, hash 533105.231/1572276920.992 in 1.4 ms
18:16:57: Verge 2054285 not reporting
18:16:58: XVG 2054286 - diff 10123889.088431366 job 526 to 146/146/146 clients, hash 534306.585/1175183041.707 in 1.5 ms
18:17:18: Verge 2054286 not reporting
18:17:19: XVG 2054287 - diff 10123889.088431366 job 527 to 146/146/146 clients, hash 539064.468/1175183041.707 in 1.3 ms
18:18:01: Verge 2054289 not reporting
18:18:02: XVG 2054290 - diff 10123889.088431366 job 528 to 148/148/148 clients, hash 569413.579/1207827015.087 in 1.4 ms
18:18:22: Verge 2054290 not reporting
18:18:23: XVG 2054291 - diff 10123889.088431366 job 529 to 148/148/148 clients, hash 573013.264/1207827015.087 in 1.4 ms
18:18:43: Verge 2054291 not reporting
18:18:44: XVG 2054292 - diff 10123889.088431366 job 52a to 147/147/147 clients, hash 568189.734/1207827015.087 in 1.4 ms
18:19:04: Verge 2054292 not reporting
18:19:05: XVG 2054293 - diff 10123889.088431366 job 52b to 147/147/147 clients, hash 564438.892/1242336358.376 in 1.4 ms
18:19:26: XVG 2054293 - diff 10123889.088431366 job 52c to 147/147/147 clients, hash 583800.714/1242336358.376 in 1.4 ms

Any ideas why is not working, a different coin for the same pool is working great... got a lot of those "Verge 2054XXX not reporting" 

this is my config file, i am running Ubuntu 16 on a VPS

rpcuser=yiimprpc
rpcpassword=XXXXXXXXXXXXX
rpcport=5610
rpcthreads=8
rpcallowip=127.0.0.1
# onlynet=ipv4
maxconnections=12
daemon=1
algo=blake
gen=0

alertnotify=echo %s | mail -s "Verge alert!" info@clouddatatech.net
blocknotify=/var/stratum/blocknotify pool2mine.com:5766 561 %s

**Comment by justinvforvendetta** [comment] 2018-04-12 22:00
you don't need gen=0
also, make sure you are using 4.0clearnet branch

**Comment by jrsikors** [comment] 2018-04-13 16:05
duplicate of #708 i think... will consolidate both of you on that issue

@pool2mine feel free to re-open if you feel your issue is different .. and make sure you did what justin suggested about the gen=0 and 4.0clearnet

**Closed by jrsikors** 2018-04-13 16:05 UTC
