### ISSUE TITLE
Any 5.0 Nodes for non tor?

### ISSUE THREAD

**Issue by cod3gen** [vergecurrency/VERGE#869] opened 2019-02-09 10:48 UTC
I'm have problems getting connected. Are there any nodes running 5.0 without tor available?

**Comment by marpme** [comment] 2019-02-17 10:45
Just checkout the current master and build it, there should be one or two if you are lucky. 
But not explicitly 5.0 clearnet nodes.

**Comment by cod3gen** [comment] 2019-05-28 19:11
Feel like this is an issue @marpme... There is virtually 0 connections to get without using Tor. And Tor slows down things which may lead to more Orphans on Pool. I was and partially are running Clearnet from the old daemon which gets a very decent amount of connections outside of Tor. Trying to add nodes from those daemon manually only works for a couple minutes before they are disconnected.

**Comment by justinvforvendetta** [comment] 2019-05-30 19:54
"addr" : "47.52.66.112:36790",
        "addr" : "47.91.164.236:21102",
        "addr" : "145.239.0.126:21102",
        "addr" : "47.90.23.3:21102",
        "addr" : "95.179.143.233:21102",
        "addr" : "94.23.9.142:21102",
        "addr" : "149.56.182.120:21102",
        "addr" : "37.143.14.228:21102",
        "addr" : "54.39.46.108:21102",
        "addr" : "47.52.62.17:48508",

**Comment by cod3gen** [comment] 2019-05-30 20:02
Ill give them a spin

**Comment by cod3gen** [comment] 2019-05-31 04:32
Had 11 connections yesterday, while there are 0 connections left today. Started with peers and banlist removed yesterday.

```
verge-cli --rpcconnect=192.168.2.30 getpeerinfo
[
]
```

```
verge-cli --rpcconnect=192.168.2.30 getnetworkinfo
{
  "version": 5010200,
  "subversion": "/verge:5.1.2/",
  "protocolversion": 90007,
  "localservices": "0000000000000407",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 0,
  "networks": [
```
Debug.log:
https://paste.ubuntu.com/p/Vfwt2zHkFJ/

There is lots of `socket recv error``s, and also many `bad peer: peer's connecting subver is , which is too old! - disconnecting!` subver is not properly included in this string, could there be issues with peer matching?

I think this can also be related to #916..

**Comment by cod3gen** [comment] 2019-05-31 12:00
It seems that the daemon is banning all nodes with the reason `node misbehaving`. Example;

```
{
    "address": "18.85.192.253/32",
    "banned_until": 1559373943,
    "ban_created": 1559287543,
    "ban_reason": "node misbehaving"
  },
  {
    "address": "23.129.64.154/32",
    "banned_until": 1559365206,
    "ban_created": 1559278806,
    "ban_reason": "node misbehaving"
  },
  {
    "address": "23.129.64.156/32",
    "banned_until": 1559377176,
    "ban_created": 1559290776,
    "ban_reason": "node misbehaving"
  },
  {
    "address": "23.129.64.159/32",
    "banned_until": 1559339405,
    "ban_created": 1559253005,
    "ban_reason": "node misbehaving"
  },
  {
    "address": "23.129.64.213/32",
    "banned_until": 1559357580,
    "ban_created": 1559271180,
    "ban_reason": "node misbehaving"
  },
  {
    "address": "3
```

+ probably 50 more. The list is long, all with same reason.

**Comment by marpme** [comment] 2019-05-31 13:38
@cod3gen Seems like clearnet nodes are way too outdated and send wrong/broken version messages to the newer nodes. As it isn't even able to parse the version string from the incoming node.

The socket connection error might be caused due to the different versions we are talking about, but it definitely looks odd tho. 

And I don't think that this issue is related to #916 as this is mainly caused by TOR and its timeoffs

**Comment by cod3gen** [comment] 2019-05-31 14:48
@marpme Its not limited to clearnet nodes.. It includes daemons on latest version too.

Running clear banned command did not allow the daemon to try to connect to them again it seems, even though the list of banned nodes is now empty. Stopping the daemon, removing peers.dat(banlist.dat looks to be empty at only 37 bytes) and starting again allows it to start reconnecting it seems.

One of the nodes:
```
 {
    "id": 14,
    "addr": "185.220.101.32:40089",
    "addrlocal": "XXX:21102",
    "addrbind": "XXX:21102",
    "services": "0000000000000407",
    "relaytxes": true,
    "lastsend": 1559313654,
    "lastrecv": 1559313642,
    "bytessent": 7056,
    "bytesrecv": 7737,
    "conntime": 1559313641,
    "timeoffset": 0,
    "pingtime": 0.256232,
    "minping": 0.256232,
    "version": 90007,
    "subver": "/verge:5.1.2/",
    "inbound": true,
    "addnode": false,
    "startingheight": 3171846,
    "banscore": 20,
    "synced_headers": -1,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 325,
      "feefilter": 32,
      "getheaders": 1117,
      "headers": 5273,
      "ping": 32,
      "pong": 32,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 131
    },
    "bytesrecv_per_msg": {
      "addr": 80,
      "feefilter": 32,
      "getaddr": 24,
      "getheaders": 1117,
      "headers": 6175,
      "ping": 32,
      "pong": 32,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 131
    }
  }
```

Which also is in the list of misbehaving nodes;
```
{
    "address": "185.220.101.32/32",
    "banned_until": 1559352273,
    "ban_created": 1559265873,
    "ban_reason": "node misbehaving"
  },

```

I have now started daemon with debug=net to see if this gives any more sensible output in debug.log

**Comment by justinvforvendetta** [comment] 2019-05-31 17:32
so yesterday, i started a new 18.04 server, cloned and compiled. 

i now have 12 peers. my peer is 159.89.46.252:21102

    ```
"addr": "94.23.9.142:21102"
    "addr": "198.98.57.10:21102"
    "addr": "185.202.152.1:48950"
    "addr": "193.70.35.154:37230"
    "addr": "203.198.146.232:49804"
    "addr": "167.114.159.30:37480"
    "addr": "209.97.136.144:32352"
    "addr": "167.114.159.30:39398"
    "addr": "167.114.159.30:52548"
    "addr": "209.97.155.120:39032"
    "addr": "203.198.146.232:48056"
    "addr": "185.202.152.1:58560"
```

**Comment by justinvforvendetta** [comment] 2019-05-31 17:35
going to close this as it seems clearnet peer discovery for 5.x codebase is working great. (there probably aren't many yet since tor is baked in and most people don't add -without-tor flags, but i will deploy more clearnet nodes)

**Closed by justinvforvendetta** 2019-05-31 17:35 UTC

**Comment by cod3gen** [comment] 2019-05-31 17:46
Hmmm. So i have problems on three different 18.04 servers, while your is working. Wierd.

**Comment by marpme** [comment] 2019-05-31 17:47
Can confirm that there are no issues on mac either

**Comment by justinvforvendetta** [comment] 2019-05-31 17:51
@cod3gen just because i closed it, doesn't mean you cant post in here again if you continue to have issues. please feel free to paste more debug in here if it continues. i experienced some peer issues when we released 5.0 but now at this point, they seem to be gone. have you made sure you pulled  the latest changes?

**Comment by cod3gen** [comment] 2019-05-31 17:54
at the moment i'm on bugfix-blocktemplate* branch, however other than the node you added there is no changes on daemon there i think.  How is your VERGE.conf file, @justinvforvendetta

**Comment by justinvforvendetta** [comment] 2019-05-31 17:57
rpcuser=xxxxxxxxx
rpcpassword=xxxxxxxxxx
rpcport=20102
port=21102
daemon=1
listen=1
server=1
deprecatedrpc=accounts

**Comment by cod3gen** [comment] 2019-05-31 17:57
Mine;

```
rpcuser=yeah
rpcpassword=sure
rpcport=numbers
rpcthreads=12
rpcallowip=some
rpcallowip=1some
# onlynet=ipv4
maxconnections=256
daemon=1
server=1
listen=1
txindex=1
#gen=0

addnode=159.89.46.252:21102
addnode=94.23.9.142:21102
addnode=198.98.57.10:21102
addnode=185.202.152.1:48950
addnode=193.70.35.154:37230
addnode=203.198.146.232:49804
addnode=167.114.159.30:37480
addnode=209.97.136.144:32352
addnode=167.114.159.30:52548
addnode=209.97.155.120:39032
addnode=203.198.146.232:48056
addnode=185.202.152.1:58560

alertnotify=echo %s | mail -s "VERGE Scrypt alert!" XX
blocknotify=XXX
```

**Comment by cod3gen** [comment] 2019-05-31 17:58
Ok. More or less the same, except deprecatedrpc and txindex.

**Comment by justinvforvendetta** [comment] 2019-05-31 18:33
i did add one more v5 clearnet ip to the chainparams, ill add several more tonight as well.

**Comment by cod3gen** [comment] 2019-05-31 19:28
Snippet of output with debug=net;

```
2019-05-31T17:55:54Z connect() to 198.27.82.41:21102 failed after select(): Connection refused (111)
2019-05-31T17:55:54Z received: headers (83 bytes) peer=0
2019-05-31T17:55:54Z sending getheaders (1093 bytes) peer=0
2019-05-31T17:55:54Z received header 3ab85cd9f7b974ac13d22969e31f74a7166e279ef147c06cf7c9429e70d9c013: missing prev block ca02b361a975b824951d6bb06b1caf884d6c5fd28a105312f04d8a137e58181a, sending getheaders (3171772) to end (peer=0, nUnconnectingHeaders=5)
2019-05-31T17:55:55Z received: headers (34525 bytes) peer=0
2019-05-31T17:55:55Z sending reject (31 bytes) peer=0
2019-05-31T17:55:55Z ProcessMessages(headers, 34525 bytes): Exception 'ReadCompactSize(): size too large: iostream error' caught
2019-05-31T17:55:55Z ProcessMessages(headers, 34525 bytes) FAILED peer=0
2019-05-31T17:55:55Z connection to 203.198.146.232:49804 timeout
2019-05-31T17:55:55Z trying connection 167.114.159.30:37480 lastseen=0.0hrs
2019-05-31T17:55:55Z connect() to 167.114.159.30:37480 failed after select(): Connection refused (111)
2019-05-31T17:55:55Z Added connection peer=13
2019-05-31T17:55:55Z connection from 67.44.224.30:27786 accepted
2019-05-31T17:55:56Z trying connection 209.97.136.144:32352 lastseen=0.0hrs
2019-05-31T17:55:57Z received: version (104 bytes) peer=13
2019-05-31T17:55:57Z bad peer: peer's connecting subver is , which is too old! - disconnecting!
2019-05-31T17:55:57Z sending version (107 bytes) peer=13
2019-05-31T17:55:57Z send version message: version 90007, blocks=3171772, us=[::]:0, peer=13
2019-05-31T17:55:57Z sending verack (0 bytes) peer=13
2019-05-31T17:55:57Z receive version message: /XVG:2.1.0/: version 90001, blocks=1845184, us=151.80.23.169:21102, peer=13
2019-05-31T17:55:57Z added time data, samples 6, offset -2 (+0 minutes)
2019-05-31T17:55:57Z disconnecting peer=13
2019-05-31T17:55:57Z Cleared nodestate for peer=13
2019-05-31T17:56:00Z trying connection 217.182.196.200:44432 lastseen=264.0hrs
2019-05-31T17:56:01Z received: headers (83 bytes) peer=6
2019-05-31T17:56:01Z sending getheaders (1093 bytes) peer=6
2019-05-31T17:56:01Z received header 3ab85cd9f7b974ac13d22969e31f74a7166e279ef147c06cf7c9429e70d9c013: missing prev block ca02b361a975b824951d6bb06b1caf884d6c5fd28a105312f04d8a137e58181a, sending getheaders (3171772) to end (peer=6, nUnconnectingHeaders=2)
2019-05-31T17:56:01Z connection to 209.97.136.144:32352 timeout
2019-05-31T17:56:01Z trying connection 167.114.159.30:52548 lastseen=0.0hrs
2019-05-31T17:56:01Z connect() to 167.114.159.30:52548 failed after select(): Connection refused (111)
2019-05-31T17:56:02Z received: headers (34525 bytes) peer=6
2019-05-31T17:56:02Z sending reject (31 bytes) peer=6
2019-05-31T17:56:02Z ProcessMessages(headers, 34525 bytes): Exception 'ReadCompactSize(): size too large: iostream error' caught
2019-05-31T17:56:02Z ProcessMessages(headers, 34525 bytes) FAILED peer=6
2019-05-31T17:56:02Z trying connection 209.97.155.120:39032 lastseen=0.0hrs
2019-05-31T17:56:03Z received: inv (289 bytes) peer=0
2019-05-31T17:56:03Z got inv: tx e5bd3a0ed125faec4522daa0417b0ac934c1ff97fb0e94797e256ef4d75adc05  new peer=0
2019-05-31T17:56:03Z askfor tx e5bd3a0ed125faec4522daa0417b0ac934c1ff97fb0e94797e256ef4d75adc05  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z got inv: tx a18d725b2428508dbfe09ea8088fa13c07201645b0ccea5fb9b56cd0de54010e  new peer=0
2019-05-31T17:56:03Z askfor tx a18d725b2428508dbfe09ea8088fa13c07201645b0ccea5fb9b56cd0de54010e  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z got inv: tx 4fa52d70b723ef57273a0c5b41d55e70e87e0387f4c23c3f050a7d31f542a009  new peer=0
2019-05-31T17:56:03Z askfor tx 4fa52d70b723ef57273a0c5b41d55e70e87e0387f4c23c3f050a7d31f542a009  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z got inv: tx 6bba13625f2bb34bfb6ff46863c3b3a4daa5b657f0b193eba9f8cd35e8e4e6f5  new peer=0
2019-05-31T17:56:03Z askfor tx 6bba13625f2bb34bfb6ff46863c3b3a4daa5b657f0b193eba9f8cd35e8e4e6f5  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z got inv: tx 59243f0e36b921c5c68dea2a1e403f0100fd640b8f50db0b4b8c4dbbcb4b50bc  new peer=0
2019-05-31T17:56:03Z askfor tx 59243f0e36b921c5c68dea2a1e403f0100fd640b8f50db0b4b8c4dbbcb4b50bc  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z got inv: tx 8198441d5a6e708baeffebbe163d384e089f6f0f667c7d7e3f3369ee5914dca5  new peer=0
2019-05-31T17:56:03Z askfor tx 8198441d5a6e708baeffebbe163d384e089f6f0f667c7d7e3f3369ee5914dca5  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z got inv: tx 9795f8dad4936c2d275443c6fa332ef69f6a261c5f6c3d7b2354da8902781081  new peer=0
2019-05-31T17:56:03Z askfor tx 9795f8dad4936c2d275443c6fa332ef69f6a261c5f6c3d7b2354da8902781081  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z got inv: tx 11f0b9841e4b11277a025ed8d82efe0bbe8fe60609e8820c5a0c681f2c8d6d51  new peer=0
2019-05-31T17:56:03Z askfor tx 11f0b9841e4b11277a025ed8d82efe0bbe8fe60609e8820c5a0c681f2c8d6d51  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z Requesting tx e5bd3a0ed125faec4522daa0417b0ac934c1ff97fb0e94797e256ef4d75adc05 peer=0
2019-05-31T17:56:03Z Requesting tx a18d725b2428508dbfe09ea8088fa13c07201645b0ccea5fb9b56cd0de54010e peer=0
2019-05-31T17:56:03Z Requesting tx 4fa52d70b723ef57273a0c5b41d55e70e87e0387f4c23c3f050a7d31f542a009 peer=0
2019-05-31T17:56:03Z Requesting tx 6bba13625f2bb34bfb6ff46863c3b3a4daa5b657f0b193eba9f8cd35e8e4e6f5 peer=0
2019-05-31T17:56:03Z Requesting tx 59243f0e36b921c5c68dea2a1e403f0100fd640b8f50db0b4b8c4dbbcb4b50bc peer=0
2019-05-31T17:56:03Z Requesting tx 8198441d5a6e708baeffebbe163d384e089f6f0f667c7d7e3f3369ee5914dca5 peer=0
2019-05-31T17:56:03Z Requesting tx 9795f8dad4936c2d275443c6fa332ef69f6a261c5f6c3d7b2354da8902781081 peer=0
2019-05-31T17:56:03Z Requesting tx 11f0b9841e4b11277a025ed8d82efe0bbe8fe60609e8820c5a0c681f2c8d6d51 peer=0
2019-05-31T17:56:03Z sending getdata (289 bytes) peer=0
2019-05-31T17:56:03Z received: tx (196 bytes) peer=0
2019-05-31T17:56:03Z ERROR: AcceptToMemoryPoolWorker: Consensus::CheckTxInputs: e5bd3a0ed125faec4522daa0417b0ac934c1ff97fb0e94797e256ef4d75adc05, bad-txns-premature-spend-of-coinbase, tried to spend coinbase at depth 74 (code 16)
2019-05-31T17:56:03Z sending reject (73 bytes) peer=0
2019-05-31T17:56:03Z received: tx (229 bytes) peer=0
2019-05-31T17:56:03Z received: tx (229 bytes) peer=0
2019-05-31T17:56:03Z received: tx (230 bytes) peer=0
2019-05-31T17:56:03Z FindStealthTransactions() tx: a18d725b2428508dbfe09ea8088fa13c07201645b0ccea5fb9b56cd0de54010e
2019-05-31T17:56:03Z askfor tx 2bb57d6fb4737c5aad22a33e410668fa1a25d36a47f491c105bc75d4e67c4ad6  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z Requesting tx 2bb57d6fb4737c5aad22a33e410668fa1a25d36a47f491c105bc75d4e67c4ad6 peer=0
2019-05-31T17:56:03Z sending getdata (37 bytes) peer=0
2019-05-31T17:56:03Z received: tx (230 bytes) peer=0
2019-05-31T17:56:03Z FindStealthTransactions() tx: 4fa52d70b723ef57273a0c5b41d55e70e87e0387f4c23c3f050a7d31f542a009
2019-05-31T17:56:03Z askfor tx d4b1ab697a1293bfe7055731dc5dfe85926758d79f4cafbda3947d981303bfdc  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z Requesting tx d4b1ab697a1293bfe7055731dc5dfe85926758d79f4cafbda3947d981303bfdc peer=0
2019-05-31T17:56:03Z sending getdata (37 bytes) peer=0
2019-05-31T17:56:03Z received: tx (230 bytes) peer=0
2019-05-31T17:56:03Z received: tx (230 bytes) peer=0
2019-05-31T17:56:03Z askfor tx 926533f8cb28cea771f2d6c79e993edd362e609b4658a2a475a5d8bc3cce08ae  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z received: tx (230 bytes) peer=0
2019-05-31T17:56:03Z askfor tx 926533f8cb28cea771f2d6c79e993edd362e609b4658a2a475a5d8bc3cce08ae  0 (00:00:00Z) peer=0
2019-05-31T17:56:03Z Requesting tx 926533f8cb28cea771f2d6c79e993edd362e609b4658a2a475a5d8bc3cce08ae peer=0
2019-05-31T17:56:03Z sending getdata (37 bytes) peer=0
2019-05-31T17:56:03Z received: tx (230 bytes) peer=0
2019-05-31T17:56:03Z FindStealthTransactions() tx: 8198441d5a6e708baeffebbe163d384e089f6f0f667c7d7e3f3369ee5914dca5
2019-05-31T17:56:03Z FindStealthTransactions() tx: 11f0b9841e4b11277a025ed8d82efe0bbe8fe60609e8820c5a0c681f2c8d6d51
2019-05-31T17:56:03Z received: notfound (37 bytes) peer=0
2019-05-31T17:56:03Z received: notfound (37 bytes) peer=0
2019-05-31T17:56:03Z received: notfound (37 bytes) peer=0
2019-05-31T17:56:05Z connection to 217.182.196.200:44432 timeout
2019-05-31T17:56:07Z connection to 209.97.155.120:39032 timeout
2019-05-31T17:56:07Z trying connection 203.198.146.232:48056 lastseen=0.0hrs
2019-05-31T17:56:09Z sending ping (8 bytes) peer=6
2019-05-31T17:56:09Z received: ping (8 bytes) peer=6
2019-05-31T17:56:09Z sending pong (8 bytes) peer=6
2019-05-31T17:56:09Z received: pong (8 bytes) peer=6
2019-05-31T17:56:09Z received: headers (83 bytes) peer=0
2019-05-31T17:56:09Z sending getheaders (1093 bytes) peer=0
2019-05-31T17:56:09Z received header a098f2df338b35b60bfc2d40874d3d60e47c477f76f7235792b1172c81522d70: missing prev block 3ab85cd9f7b974ac13d22969e31f74a7166e279ef147c06cf7c9429e70d9c013, sending getheaders (3171772) to end (peer=0, nUnconnectingHeaders=6)
2019-05-31T17:56:09Z received: headers (34607 bytes) peer=0
2019-05-31T17:56:09Z sending reject (31 bytes) peer=0
2019-05-31T17:56:09Z ProcessMessages(headers, 34607 bytes): Exception 'ReadCompactSize(): size too large: iostream error' caught
2019-05-31T17:56:09Z ProcessMessages(headers, 34607 bytes) FAILED peer=0
2019-05-31T17:56:12Z connection to 203.198.146.232:48056 timeout
2019-05-31T17:56:12Z received: headers (83 bytes) peer=0
2019-05-31T17:56:12Z sending getheaders (1093 bytes) peer=0
2019-05-31T17:56:12Z received header 000000000002e70784efd1611f3a1ce41a519f8fac1497ed77df431fcddf6c16: missing prev block a098f2df338b35b60bfc2d40874d3d60e47c477f76f7235792b1172c81522d70, sending getheaders (3171772) to end (peer=0, nUnconnectingHeaders=7)
2019-05-31T17:56:13Z received: headers (34689 bytes) peer=0
2019-05-31T17:56:13Z sending reject (31 bytes) peer=0
2019-05-31T17:56:13Z ProcessMessages(headers, 34689 bytes): Exception 'ReadCompactSize(): size too large: iostream error' caught
2019-05-31T17:56:13Z ProcessMessages(headers, 34689 bytes) FAILED peer=0
2019-05-31T17:56:13Z trying connection 185.202.152.1:58560 lastseen=0.0hrs
2019-05-31T17:56:14Z trying connection 35.163.12.21:46796 lastseen=170.7hrs
2019-05-31T17:56:15Z CreateNewBlock(): block weight: 11480 txs: 11 fees: 1100000 sigops 488
2019-05-31T17:56:16Z sending ping (8 bytes) peer=0
2019-05-31T17:56:16Z received: ping (8 bytes) peer=0
2019-05-31T17:56:16Z sending pong (8 bytes) peer=0
2019-05-31T17:56:16Z received: pong (8 bytes) peer=0
2019-05-31T17:56:18Z connection to 185.202.152.1:58560 timeout
2019-05-31T17:56:19Z received: headers (83 bytes) peer=6
2019-05-31T17:56:19Z sending getheaders (1093 bytes) peer=6
2019-05-31T17:56:19Z received header a098f2df338b35b60bfc2d40874d3d60e47c477f76f7235792b1172c81522d70: missing prev block 3ab85cd9f7b974ac13d22969e31f74a7166e279ef147c06cf7c9429e70d9c013, sending getheaders (3171772) to end (peer=6, nUnconnectingHeaders=3)
2019-05-31T17:56:19Z connection to 35.163.12.21:46796 timeout
2019-05-31T17:56:20Z received: headers (34607 bytes) peer=6
2019-05-31T17:56:20Z sending reject (31 bytes) peer=6
2019-05-31T17:56:20Z ProcessMessages(headers, 34607 bytes): Exception 'ReadCompactSize(): size too large: iostream error' caught
2019-05-31T17:56:20Z ProcessMessages(headers, 34607 bytes) FAILED peer=6
2019-05-31T17:56:23Z Syncing txindex with block chain from height 477877
2019-05-31T17:56:25Z trying connection 118.190.140.184:15521 lastseen=310.1hrs
2019-05-31T17:56:26Z received: headers (83 bytes) peer=0
2019-05-31T17:56:26Z sending getheaders (1093 bytes) peer=0
2019-05-31T17:56:26Z received header 0000000000019569b444a7bf3cef80a8913af638319c35f55de1d4584ab86263: missing prev block 000000000002e70784efd1611f3a1ce41a519f8fac1497ed77df431fcddf6c16, sending getheaders (3171772) to end (peer=0, nUnconnectingHeaders=8)
2019-05-31T17:56:26Z received: headers (34771 bytes) peer=0
2019-05-31T17:56:26Z sending reject (31 bytes) peer=0
2019-05-31T17:56:26Z ProcessMessages(headers, 34771 bytes): Exception 'ReadCompactSize(): size too large: iostream error' caught
2019-05-31T17:56:26Z ProcessMessages(headers, 34771 bytes) FAILED peer=0
2019-05-31T17:56:30Z connection to 118.190.140.184:15521 timeout
2019-05-31T17:56:35Z received: headers (165 bytes) peer=0
2019-05-31T17:56:35Z sending getheaders (1093 bytes) peer=0
2019-05-31T17:56:35Z received header 0000000000029a04ee7d1926193b21c96780ffaa50a130a8d7067a0c6fcd7919: missing prev block 000000000002e70784efd1611f3a1ce41a519f8fac1497ed77df431fcddf6c16, sending getheaders (3171772) to end (peer=0, nUnconnectingHeaders=9)
2019-05-31T17:56:35Z received: headers (34853 bytes) peer=0
2019-05-31T17:56:35Z sending reject (31 bytes) peer=0
2019-05-31T17:56:35Z ProcessMessages(headers, 34853 bytes): Exception 'ReadCompactSize(): size too large: iostream error' caught
2019-05-31T17:56:35Z ProcessMessages(headers, 34853 bytes) FAILED peer=0
2019-05-31T17:56:35Z received: headers (165 bytes) peer=6
2019-05-31T17:56:35Z sending getheaders (1093 bytes) peer=6
2019-05-31T17:56:35Z received header 000000000002e70784efd1611f3a1ce41a519f8fac1497ed77df431fcddf6c16: missing prev block a098f2df338b35b60bfc2d40874d3d60e47c477f76f7235792b1172c81522d70, sending getheaders (3171772) to end (peer=6, nUnconnectingHeaders=4)
2019-05-31T17:56:36Z received: headers (34771 bytes) peer=6
2019-05-31T17:56:36Z sending reject (31 bytes) peer=6
2019-05-31T17:56:36Z ProcessMessages(headers, 34771 bytes): Exception 'ReadCompactSize(): size too large: iostream error' caught
2019-05-31T17:56:36Z ProcessMessages(headers, 34771 bytes) FAILED peer=6
2019-05-31T17:56:37Z trying connection 159.89.202.56:21102 lastseen=275.6hrs
2019-05-31T17:56:38Z connect() to 159.89.202.56:21102 failed after select(): No route to host (113)
2019-05-31T17:56:42Z received: headers (83 bytes) peer=0
2019-05-31T17:56:42Z sending getheaders (1093 bytes) peer=0
2019-05-31T17:56:42Z received header 1a813eb148c8d7d7722c4962fb036e5e474799929a0321e3964f22f24e9730d6: missing prev block 99fb12e980c2587fe7848a03adc932fb1715f9a83d2f8df0729bee2fce7afac8, sending getheaders (3171772) to end (peer=0, nUnconnectingHeaders=10)
2019-05-31T17:56:42Z Misbehaving: 159.89.46.252:21102 peer=0 (0 -> 20)
2019-05-31T17:56:42Z received: headers (34935 bytes) peer=0
```

**Comment by marpme** [comment] 2019-05-31 19:40
On which branch are you currently? @cod3gen

**Comment by cod3gen** [comment] 2019-05-31 20:26
At the time of that log, i was on "bugfix-blocktemplate-creation-for-different-algos".

I have now moved over to latest master, removed all contents of .VERGE dir except config and wallet. almost one hour since daemon was started and getblockchain is now blocks: 0 - headers: 140000.

**Comment by justinvforvendetta** [comment] 2019-05-31 22:33
i just launched 2 more clearnet nodes and they connected right away after a .conf

heres my conf:
```
addnode=159.89.46.252:21102
addnode=139.59.34.170:21102
addnode=134.209.197.243:21102
addnode=94.23.9.142:21102
addnode=198.98.57.10:21102
addnode=185.202.152.1:48950
addnode=193.70.35.154:37230
addnode=203.198.146.232:49804
addnode=167.114.159.30:37480
addnode=209.97.136.144:32352
addnode=167.114.159.30:39398
addnode=167.114.159.30:52548
addnode=209.97.155.120:39032
addnode=203.198.146.232:48056
addnode=185.202.152.1:58560
maxconnections=250
daemon=1
listen=1
server=1
txindex=1
```
