### ISSUE TITLE
ERROR: Error reading proxy response verge

### ISSUE THREAD

**Issue by zijieli111** [vergecurrency/VERGE#772] opened 2018-06-21 04:55 UTC
VERGE version v4.0.2.0-c3a04c0-funky-beta (2018-04-12 06:06:47 +0000)
Using OpenSSL version OpenSSL 1.0.2k  26 Jan 2017
Startup time: 06/21/18 04:46:08
Default data directory C:\Users\Administrator\AppData\Roaming\VERGE
Default mining hash algorithm: scrypt
Used data directory C:\Users\Administrator\AppData\Roaming\VERGE
scrypt: using scrypt-sse2 as detected.
dbenv.open LogDir=C:\Users\Administrator\AppData\Roaming\VERGE\database ErrorFile=C:\Users\Administrator\AppData\Roaming\VERGE\db.log
Bound to 127.0.0.1:21102
TOR thread started.
AddLocal(lpqt2u5a66fomki2.onion:21102,4)
Loading block index...
Opening LevelDB in C:\Users\Administrator\AppData\Roaming\VERGE\txleveldb
Transaction index version is 70509
Opened LevelDB successfully
LoadBlockIndex(): hashBestChain=00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278  height=0  trust=1  date=10/09/14 18:22:44
LoadBlockIndex(): synchronized checkpoint 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
Verifying last 0 blocks at level 1
 block index              13ms
Loading wallet...
No OBFS4 found, not using it.
nFileVersion = 4000200
 wallet                 3968ms
Loading addresses...
Loaded 7 addresses from peers.dat  0ms
mapBlockIndex.size() = 1
nBestHeight = 0
setKeyPool.size() = 100
mapWallet.size() = 0
mapAddressBook.size() = 1
Done loading
Loading addresses from .onion seeds
7 addresses found from .onion seeds
ThreadOnionSeed exited
ThreadMessageHandler started
ThreadSocketHandler started
Flushed 7 addresses to peers.dat  5ms
trying connection ie4vffvggaz6xhbj.onion:21102 lastseen=73.2hrs
SOCKS5 connecting ie4vffvggaz6xhbj.onion
refreshWallet
ipcThread started
ERROR: Error reading proxy response
trying connection plxs66tqlzbnh3ua.onion:21102 lastseen=73.2hrs
SOCKS5 connecting plxs66tqlzbnh3ua.onion
ERROR: Error reading proxy response
trying connection 5onui2lfl3iwdhrf.onion:21102 lastseen=97.9hrs
SOCKS5 connecting 5onui2lfl3iwdhrf.onion
ERROR: Error reading proxy response
trying connection kw5bdikypbbxaf2g.onion:21102 lastseen=92.7hrs
SOCKS5 connecting kw5bdikypbbxaf2g.onion
ERROR: Error reading proxy response
trying connection n5ln6ke2vc47glpl.onion:21102 lastseen=109.9hrs
SOCKS5 connecting n5ln6ke2vc47glpl.onion
ERROR: Error reading proxy response
trying connection 7sfrhwc6l4oohb5h.onion:21102 lastseen=152.0hrs
SOCKS5 connecting 7sfrhwc6l4oohb5h.onion
ERROR: Error reading proxy response
trying connection 5n4gl3kvntyanp63.onion:21102 lastseen=119.4hrs
SOCKS5 connecting 5n4gl3kvntyanp63.onion
ERROR: Error reading proxy response
trying connection plxs66tqlzbnh3ua.onion:21102 lastseen=73.2hrs
SOCKS5 connecting plxs66tqlzbnh3ua.onion
ERROR: Error reading proxy response
trying connection 7sfrhwc6l4oohb5h.onion:21102 lastseen=152.0hrs
SOCKS5 connecting 7sfrhwc6l4oohb5h.onion
ERROR: Error reading proxy response
trying connection ie4vffvggaz6xhbj.onion:21102 lastseen=73.3hrs
SOCKS5 connecting ie4vffvggaz6xhbj.onion
ERROR: Error reading proxy response
trying connection 5onui2lfl3iwdhrf.onion:21102 lastseen=97.9hrs
SOCKS5 connecting 5onui2lfl3iwdhrf.onion
ERROR: Error reading proxy response
trying connection plxs66tqlzbnh3ua.onion:21102 lastseen=73.3hrs
SOCKS5 connecting plxs66tqlzbnh3ua.onion
ERROR: Error reading proxy response

**Comment by jrsikors** [comment] 2018-06-21 15:43
What is the problem you are having?  Is something not working ?

**Comment by jrsikors** [comment] 2018-06-23 16:18
closing -- please post any problems you are having.  These "errors" are somewhat normal and do not mean there is an issue.  If you are having a problem somewhere and think these are the cause, please let us know where you are having problems.

**Closed by jrsikors** 2018-06-23 16:18 UTC
Labels: Tor related, help wanted
