### ISSUE TITLE
Build for Windows

### ISSUE THREAD

**Issue by nosferatu500** [vergecurrency/VERGE#767] opened 2018-06-14 10:10 UTC
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [x] I'm using Linux
    - [ ] I'm using Mac

## Any extra information that might be useful in the debugging process.

Hello guys. I have one question. I trying build Verge from source for  windows using  `easywinbuilder` and `Dockerfile`, but first & second method fail with multiple errors. Question: It's actually now or I must using another way for build Qt Wallet for Windows?

I see travis logs for windows, build log have multiple errors too, but travis have green status.

**Comment by marpme** [comment] 2018-06-14 12:13
Can't build it for windows, too. There must be something wrong with the requirements.
But the travis just walks through easily:

https://travis-ci.org/vergecurrency/VERGE/jobs/390954743

If you want you can try using linux for building windows.

**Comment by jrsikors** [comment] 2018-06-14 20:35
Yeah I gave this a shot as well and gave up a month or so ago.  We'll probably need to write a clear step-by-step guide after the new codebase.

Will flag this as a duplicate of #717  , keep all "Windows Compiling" issues under there.

**Closed** 2018-06-14 20:36 UTC
Labels: Compile Bug, duplicate

**Comment by justinvforvendetta** [comment] 2018-06-14 22:06
the new codebase will be very easy to compile for any platform =]
