### ISSUE TITLE
Issue syncing blockchain

### ISSUE THREAD

**Issue by hellquist413** [vergecurrency/VERGE#265] opened 2018-01-02 13:56 UTC
OSX High Sierra issue.

Trying to sync the blockchain downloaded from https://verge-blockchain.com/howto and following the steps on the website. I'm still getting out of sync message, and checking the log it keeps getting timed-out messages, any suggestions?

VERGE version v2.1.0.0-1af8bfd-funky-beta (2017-12-31 21:16:52 -0700)
Using OpenSSL version OpenSSL 1.0.2n  7 Dec 2017
Startup time: 01/02/18 13:52:30
Default data directory /Users/hellquist/Library/Application Support/VERGE
Default mining hash algorithm: scrypt
Used data directory /Users/hellquist/Library/Application Support/VERGE
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/Users/hellquist/Library/Application Support/VERGE/database ErrorFile=/Users/hellquist/Library/Application Support/VERGE/db.log
Bound to [::]:21102
Bound to 0.0.0.0:21102
Loading block index...
Opening LevelDB in /Users/hellquist/Library/Application Support/VERGE/txleveldb
Transaction index version is 70509
Opened LevelDB successfully
LoadBlockIndex(): hashBestChain=00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278  height=0  trust=1  date=10/09/14 18:22:44
LoadBlockIndex(): synchronized checkpoint 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
Verifying last 0 blocks at level 1
 block index              40ms
Loading wallet...
nFileVersion = 2010000
 wallet                  355ms
Loading addresses...
Loaded 5 addresses from peers.dat  6ms
mapBlockIndex.size() = 1
nBestHeight = 0
setKeyPool.size() = 100
mapWallet.size() = 0
mapAddressBook.size() = 1
Done loading
ThreadDNSAddressSeed started
Loading addresses from DNS seeds (could take a while)
ThreadMapPort started
ThreadSocketHandler started
5 addresses found from DNS seeds
ThreadDNSAddressSeed exited
ThreadOpenAddedConnections started
ThreadOpenAddedConnections exited
ThreadOpenConnections started
ThreadMessageHandler started
ThreadStakeMinter started
CPUMiner started for proof-of-stake
Flushed 5 addresses to peers.dat  1ms
trying connection 105.228.198.44:21102 lastseen=109.1hrs
GetMyExternalIP() received [213.113.250.230] 213.113.250.230:0
GetMyExternalIP() returned 213.113.250.230
AddLocal(213.113.250.230:21102,4)
refreshWallet
UPnP: ExternalIPAddress = 213.113.250.230
AddLocal(213.113.250.230:21102,3)
UPnP Port Mapping successful.
connection timeout
trying connection 98.5.123.15:21102 lastseen=94.5hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=104.3hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=109.1hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=94.5hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=104.4hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=94.5hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=104.4hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=109.1hrs
connection timeout
trying connection 104.131.144.82:21102 lastseen=87.5hrs
connected 104.131.144.82:21102
send version message: version 90001, blocks=0, us=213.113.250.230:21102, them=104.131.144.82:21102, peer=104.131.144.82:21102
socket closed
disconnecting node 104.131.144.82:21102
trying connection 138.201.91.159:21102 lastseen=104.4hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=104.4hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=104.4hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=94.5hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=104.4hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=104.4hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=104.4hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=109.1hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=109.1hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=94.5hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=109.1hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=94.5hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=104.4hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=104.4hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=94.5hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=94.5hrs
Flushed 5 addresses to peers.dat  11ms
connection timeout
trying connection 98.5.123.15:21102 lastseen=94.5hrs

**Comment by NERON** [comment] 2018-01-02 14:12
I think it's not Verge issue, check your firewall settings.

**Comment by hellquist413** [comment] 2018-01-02 14:22
This is while the firewall is turned off..

**Comment by mjanssen** [comment] 2018-01-02 14:31
Having the same issue.

```
trying connection 138.201.91.159:21102 lastseen=77.4hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=91.4hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=80.1hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=80.1hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=91.4hrs
```

**Comment by mik3ondop3** [comment] 2018-01-02 14:54
yes i have the same problem, i dont use a firewall
![screen shot 2018-01-02 at 16 53 35](https://user-images.githubusercontent.com/34998751/34487571-8eb4c586-efdd-11e7-8a38-f2eb3d03bf7d.png)

**Comment by benammann** [comment] 2018-01-02 15:06
looks like a firewall problem.

Maybe you could try compiling the new version at your own, its running way much better.

<img width="743" alt="screen shot 2018-01-02 at 16 05 41" src="https://user-images.githubusercontent.com/24310981/34487963-d1dec1b0-efd6-11e7-9c0f-ca0057afb612.png">

**Comment by mike2lab** [comment] 2018-01-02 15:12
this is what i did

**Comment by mike2lab** [comment] 2018-01-02 15:14
yes its working now

**Comment by chineseballer06** [comment] 2018-01-02 15:14
how do you do this?

**Comment by hellquist413** [comment] 2018-01-02 15:17
Ok, mine started syncing with network now as well. A sync bar appeared in the VERGE Qt app and it started to accept the connections.

**Comment by mike2lab** [comment] 2018-01-02 15:18
me too

![screen shot 2018-01-02 at 17 17 33](https://user-images.githubusercontent.com/34998751/34488362-df41327a-efe0-11e7-97ca-9a424183b30b.png)

**Comment by benammann** [comment] 2018-01-02 15:21
@hellquist413 

Verge-QT starts syncing ... just give it some time

please close this issue

**Comment by chineseballer06** [comment] 2018-01-02 15:22
So i have to download the blockchain first and then it will sync?

**Comment by mike2lab** [comment] 2018-01-02 15:23
i think that started syncing you dont have to

**Comment by vorlonempire** [comment] 2018-01-02 15:23
@chineseballer06  yes

**Comment by chineseballer06** [comment] 2018-01-02 15:24
I still have 0 active connections...okay i'll try adding the blockchain to the file

**Comment by benammann** [comment] 2018-01-02 15:24
@hellquist413  related to https://github.com/vergecurrency/VERGE/issues/258

please close

**Comment by hellquist413** [comment] 2018-01-02 15:25
@chineseballer06 I tried leave it on over the night but nothing happened. Had to download the blockchain and put it in the Application Support/VERGE folder then wait for it to sync again..

**Comment by chineseballer06** [comment] 2018-01-02 15:26
Okay will try, thank you for the help :)

**Closed** 2018-01-02 15:25 UTC

**Comment by chineseballer06** [comment] 2018-01-02 16:09
I don't know whats going on but I don't have the Application Support/VERGE folder when I search for the folder in finder...

**Comment by chineseballer06** [comment] 2018-01-02 16:11
please help @hellquist413

**Comment by satrya-sabeni** [comment] 2018-01-02 16:15
@chineseballer06 I just installed it, I also thought I didn't had it but make you sure you look into hidden Library in your Users/<username>/Library(this map is hidden).

**Comment by chineseballer06** [comment] 2018-01-02 16:27
@satrya-sabeni gosh thank you haha i feel dumb, but now I moved it and still not connecting to the network. Here is what my settings are if this helps...
![screen shot 2018-01-02 at 5 25 48 pm](https://user-images.githubusercontent.com/35030160/34491030-21029ab8-efe2-11e7-824f-c3e578ef8c1c.png)

**Comment by chineseballer06** [comment] 2018-01-02 16:37
[debug.log](https://github.com/vergecurrency/VERGE/files/1598080/debug.log)

**Comment by satrya-sabeni** [comment] 2018-01-02 16:39
@chineseballer06 Hi, since you just moved it the blockchain files you probably haven't synched yet because that process takes quite a bit of time. So after after you overwrite the files in the 'VERGE' folder, you need close the wallet completely and open it again. If you did it right you should see a load screen saying it's synching. This process just took 30-45 minutes with me. 

After the load screen is done(which takes about 5-10 minutes), the wallet will open but it will stay 'not synched' but you will again need to wait a quite a while. The GUI just doesn't look that responsive yet. So if you get the loading screen, just wait, it's confusing because it doesn't seem like it's doing anything but it's working, just wait 30-45 minutes.

**Comment by chineseballer06** [comment] 2018-01-02 16:44
@satrya-sabeni But I think the issue is that I can't even connect to an active connection on the Verge network to start the sync process in the first place

**Comment by satrya-sabeni** [comment] 2018-01-02 16:51
@chineseballer06 You don't need to establish any connection to sync. All you need to do is copy the files of the blockchain you downloaded and restart the app after.

**Comment by fradelo** [comment] 2018-01-02 17:00
I had the same issue. I downloaded blockchain from here [https://verge-blockchain.com/](https://verge-blockchain.com/) and followed instructions from here [https://verge-blockchain.com/howto](https://verge-blockchain.com/howto) to put it in proper location.
After that open the application you should see this
![loading_block_index](https://user-images.githubusercontent.com/35038000/34491676-00b5fba0-efed-11e7-9e9d-32eec2f93d4b.png)

This will take some time. After that the wallet will open and you will see this
![sync_blockchain](https://user-images.githubusercontent.com/35038000/34491712-3400c828-efed-11e7-9166-00fac74a8073.png)
You have to wait again this to finish since it synchronizes the blockchain to its current state.
![blockchain synced](https://user-images.githubusercontent.com/35038000/34491751-64ddabd2-efed-11e7-9573-c5ba903135d2.png)
Once it finished you will see a check mark in the lower right part of the wallet.
Windows 10 firewall asks for permissions when you first open the wallet. But you can confirm yourself
![firewall](https://user-images.githubusercontent.com/35038000/34492175-19aa7e4a-efef-11e7-955e-ca4bb84aa9ac.png)

**Comment by chineseballer06** [comment] 2018-01-02 17:15
@satrya-sabeni @fradelo thank you guys! finally got it to work, issue was i just added the downloaded blockchain without replacing the old ones.  Thanks for bearing with me, great community here! :)

**Comment by hellquist413** [comment] 2018-01-02 17:43
it said timeout for 2 hours before it connected here..

**Comment by chineseballer06** [comment] 2018-01-02 18:26
coming up on about an hour now and no sync bar being shown still.

**Comment by chineseballer06** [comment] 2018-01-02 18:41
I think I need to somehow open the port 21102 through terminal but have been struggling to find step by step how to do this.

**Comment by chineseballer06** [comment] 2018-01-02 18:54
Seems like I had a connection for brief moment, but still no progress.
![screen shot 2018-01-02 at 7 52 36 pm](https://user-images.githubusercontent.com/35030160/34495705-aa38be52-eff6-11e7-96c6-44ace9353832.png)

**Comment by fradelo** [comment] 2018-01-02 19:00
@chineseballer06 do you have use a proxy to access the internet? because i see that you enabled proxy settings in the wallet. If not please remove the option close the application download blockchain and put it in the folder that @satrya-sabeni indicated and then start the application again.

**Comment by chineseballer06** [comment] 2018-01-02 19:03
Okay will give this a shot, thanks

**Comment by chineseballer06** [comment] 2018-01-03 13:18
Finally got everything synced and running thanks for all the help.  I ended up deleting all the files and starting the process from the beginning since I didn't know I needed to download the blockchain first.  

Now I already have Verge stored on the 2.4 Electrum Wallet, is there any way to use that same address on the new 4.0 wallet? If not then my next steps would be to encrypt and backup and then I should be good to send the Verge to my new wallet correct? Just want to make sure.

**Comment by satrya-sabeni** [comment] 2018-01-03 13:25
@chineseballer06 Very happy to hear that it works for you!! I don't know exactly how to do that, like you said, you could also send it to the new address(first send a small amount to make sure it works). And yes back everything up. 
On https://www.reddit.com/r/vergecurrency/ or other verge forums you can ask it also, I definitely think people who know a lot more than me can help you.

**Comment by chineseballer06** [comment] 2018-01-03 13:27
@satrya-sabeni haha okay good idea, and yeah was frustrating but good learning experience and worth it

**Comment by satrya-sabeni** [comment] 2018-01-03 13:31
@chineseballer06 hehe I completely understand how this would be a frustrating especially to people who are less tech. But at this point it really is a raw diamond and I truly believe in time this thing will be polished up very well and a whole lot more easier to use :)

**Comment by chineseballer06** [comment] 2018-01-08 11:15
@satrya-sabeni every time you open your verge wallet does it take a while to load the block index?

**Comment by satrya-sabeni** [comment] 2018-01-11 02:33
@chineseballer06 Yeah It does take some time, I usually just let it run in the background when I open it. The new wallet update for Mac has a lot updates, so hopefully everything will be a bit easier and faster. I also use the Verge Android wallet, which works great for me.

**Comment by justinvforvendetta** [comment] 2018-01-11 02:54
you can export the private key for the electrum address and import it into your qt wallet
