### ISSUE TITLE
Error Loading BLKINDEX.dat

### ISSUE THREAD

**Issue by kosstick** [vergecurrency/VERGE#656] opened 2018-03-26 05:32 UTC
Experiencing a "error loading blkindex.dat"

Currently using OSX Sierra and previously had access the wallet on Jan 24th. Updated to the 1/30 dmg file and still no dice.

**Comment by jrsikors** [comment] 2018-03-26 14:14
you just need to go to your verge data directory ... delete out the blkindex.dat , i think there's more than 1 ., maybe like blkindex001.dat  and blkindex002.dat ... you can delete those.

Go to verge-blockchain.com and download / unzip the latest bootstrap to your data directory
https://verge-blockchain.com/

Just be very careful in your data directory.  do NOT delete your wallet.dat ... and you should have backups of your wallet.dat if you don't already .. you need to make a backup and copy it to a jump drive or something :smile:

**Comment by jrsikors** [comment] 2018-03-26 14:15
check out #642  as well.  Different issue but exactly the same resolution steps apply for you.

**Comment by kosstick** [comment] 2018-03-26 15:44
Let me do some tinkering and I will report back. I know I have tried downloading the March 23rd and 24th blockchain files and replacing them. That is what lead to the first error message.

Since my post I reinstalled verge qt. Deleted my old verge data folder and put in my wallet.dat file. It’s been naturally syncing since but I imagine this will take a very very long time.

**Comment by jrsikors** [comment] 2018-03-26 16:07
Cool -- in the future you don't need to really do a 'reinstall' of verge qt... it can't hurt... but the data directory is going to be the problem 99% of the time.

I'm glad you are smart and know how to do the wallet.dat

I would close out of Verge-QT ... download the blockchain ... unzip it to your data directory -- and then re-open verge-qt.

There's absolutely no harm in doing it your way though and letting it sync naturally.  As you said -- it just might take a day or two.  It should work fine if you have the time to wait !

**Comment by kosstick** [comment] 2018-03-26 16:08
While I wait to redownload march 24th, I wanted to add that my folder does not contain a 
blkindex001.dat but only a blk0001.dat

**Comment by jrsikors** [comment] 2018-03-26 16:16
Ya sorry I'm not in front of my wallet at the moment... blk0001.dat and blk0002.dat is right sorry !

**Comment by jrsikors** [comment] 2018-03-26 16:17
wouldn't hurt to delete your peers.dat as well after you unzip.

**Comment by kosstick** [comment] 2018-03-26 16:24
Did everything like we discussed except for deleting PEERS.DAT file. Reached 100% and received error loading blkindex.dat

**Comment by kosstick** [comment] 2018-03-26 16:25
Can I close out Verge, delete the peers.dat file and try that?

**Comment by kosstick** [comment] 2018-03-26 16:32
Update. Tried the deletion of the peers.dat file and still receiving the blkindex error once it hits 100%

**Comment by jrsikors** [comment] 2018-03-26 16:56
just to make sure we are on the same page here ... this is what you are doing:
step 1)  Delete *everything* in data directory (except wallet.dat)
step 2)  download server3_QT-Wallet_v4.x_Verge-Blockchain_2018-March-24.zip from verge-blockchain.com
step 3)  unzip server3_QT-Wallet_v4.x_Verge-Blockchain_2018-March-24.zip into your data directory
step 4)  copy wallet.dat back to data directory
Step 5)  Run verge-qt

regarding step 3... in that file , it has these files in it right:
blkindex.dat
blk0001.dat
blk0002.dat ?

There should be a db.log or debug.log in your verge data directory, could look through those and/or post here.

**Comment by jrsikors** [comment] 2018-03-26 17:01
and to clarify -- you said this which has me a little confused:

> Reached 100% and received error loading blkindex.dat

What do you mean by this?  How did you "reach 100%?"  While Verge-qt was open and running?  and While it was open and running did that error pop up ?  Or did you:
Opened verge-qt -> got to 100% -> closed verge-qt -> opened verge-qt -> now got the error

**Comment by jrsikors** [comment] 2018-03-26 17:04
Only other possibilities I can think of at this time:
  ~The current bootstrap might be corrupt -- wait until next version is uploaded later today / tomorrow and try that
  ~your virus scan or another app is locking down blkindex.dat 
 
I'd hate to suggest you let it sync for the next day or 2 from 0 blocks and then end up with the same error.

**Comment by jrsikors** [comment] 2018-03-26 17:07
unfortunately #610 and #95 are similar issues,  but neither user ever got back to us and posted their solution.

justin did suggest in one of them to let it sync from block 0

**Comment by jrsikors** [comment] 2018-03-26 17:10
I did see this on reddit as well, looks intense:
https://www.reddit.com/r/vergecurrency/comments/7sbext/verge_qt_wallet_help_w_mac_os_high_sierra/

**Comment by kosstick** [comment] 2018-03-26 23:45
There is not a blkindex.dat files or a 0002.dat files. Just a blk0001.dat file, database,peers,readme,txlevel

**Comment by jrsikors** [comment] 2018-03-27 00:09
You are correct, I'm home now and just checked.  From the reddit link i posted -- copied and pasted into a better format... you might want to delete blkindex.dat (only that one) , and then try these steps...

VergeQt 4.0.1 fork for stealth / Mac OS High Sierra Instructions if not working.

1.Backup your wallet.dat file to a safe place, found in: go,library,application support,Verge. 
2.Now go to Finder bottom left corner, type terminal, open terminal. 
3.copy & paste: xcode-select —install 
4.press enter 
5.install this then back onto terminal 
6.copy & paste: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 
7.press enter 
8.press enter again 
9.Type in password used for admin or to log in laptop, as you type you won’t see it. 
10.press enter 
11.copy & paste: brew doctor 
12.press enter 
13.copy & paste: brew install boost 
14.press enter 
15.now go to open 4.0.1 fork for stealth allow & open.

**Comment by kosstick** [comment] 2018-03-27 00:41
There is not a blkindex.dat in the folder either. is that normal?

**Comment by jrsikors** [comment] 2018-03-27 00:44
it probably tries to create, but you get the 'error loading blkindex.dat' and it goes away.

in addition to those steps -- if you wanted to -- when you open verge-qt -- watch your data directory and see if blkindex.dat is created and grows in size,, up to the point of the error .. and then disappears.

I still think the steps above will resolve you though.

**Comment by kosstick** [comment] 2018-03-27 00:49
All those things already said they were installed (I remember doing this a few months back). Would my logs help

**Comment by jrsikors** [comment] 2018-03-27 00:51
Definitely will help !

**Comment by kosstick** [comment] 2018-03-27 00:53
[debug.log](https://github.com/vergecurrency/VERGE/files/1850009/debug.log)

**Comment by kosstick** [comment] 2018-03-27 01:01
db.log is empty and has 0 size

**Comment by kosstick** [comment] 2018-03-27 01:04
Btw there doesn't seem to be blkindex.dat at any point in the folder

**Comment by jrsikors** [comment] 2018-03-27 01:18
> LoadBlockIndex(): hashBestChain=000000000000b61f87b61723ac774dc6cddda3a022ad7c59d5ea5698ad47c5a6  height=1977491  trust=1977492  date=03/23/18 23:59:32
> LoadBlockIndex(): synchronized checkpoint 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
> Verifying last 2500 blocks at level 1
> ERROR: CBlock::ReadFromDisk() : OpenBlockFile failed
> ERROR: LoadBlockIndex() : block.ReadFromDisk failed

Saw this on a bitcoin github a few years back .. something about file descriptors .. i'm not a Mac guru so
https://github.com/bitcoin/bitcoin/issues/2712

saw this post with some suggestions on increasing file descriptors
https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard

will keep looking

**Comment by jrsikors** [comment] 2018-03-27 01:20
have also seen posts about Anti-Virus being enabled causes problems with the I/O ... did you try disabling anti-virus temporarily ?

**Comment by jrsikors** [comment] 2018-03-27 01:22
saw this as well:
https://cryptocurrencytalk.com/topic/27625-cant-sync-mac-wallet-for-3-weeks-now/

you can start with post 15 and then go to page 2.. but coincidentally he refers to the same article i posted:
https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard

**Comment by jrsikors** [comment] 2018-03-27 01:23
keep in mind that all QT Wallets are basically based on the same code -- so when doing google searches -- don't feel restricted to typing "verge qt".  You can google for the problem with "bitcoin qt" and find exact same resolutions.

**Comment by kosstick** [comment] 2018-03-27 01:43
I don't believe I have anti-virus. I did just disable my icloud. hopefully that helps or fixes.

**Comment by kosstick** [comment] 2018-03-27 01:47
Also I should have Verge QT stealth transactions version installed correct upload jan 30. there is also a jan 8th version that is under 4.0.1.

Trying to see which one to be working on..

**Comment by kosstick** [comment] 2018-03-27 03:39
Seems to be hitting a dead end and naturally letting it sync seems like it’ll take a lot more than 2-3 days

**Comment by kosstick** [comment] 2018-03-27 06:13
Is there any tips or tricks to sync faster? Currently 13 active connections

**Comment by jrsikors** [comment] 2018-03-27 18:17
Sadly no ... just have to suffer through it.  the "trick" is to use a bootstrap to catch up .. but we can't use that trick :(

**Comment by merbals** [comment] 2018-03-28 08:57
Hi, I have exactly the same problem. I hadn’t opened the wallet for over a month and last night it was taking an age to update so thought I would just just use the latest bootstrap files.
Now I get the exact same error also I know another person who yesterday did the same thing and also having the exact same issue. Are the downloaded files must be corrupt?

Looks like several of us have the same problems. Just for you info.

I have done it before without any problems.

**Comment by jetpippo** [comment] 2018-03-28 11:32
Hi @jrsikors, I've been having the same problem but with windows 10.
Im really new to all this but this is what happened.
I downloaded the wallet 4.0.1 from the Verge website, when I opened it it was out of sync and had so many blocks to load (at this point i still didn't know i could download the blockchain) anyways i waited nearly 2 days for all the blocks to download and with the wallet open everytime it was getting close to finishing it went back to around 70%.
While this was happening I tried to send all my XVG to this unsynced wallet to an address i generated from there (not sure whether this is ok or not ...)
I started searching online and saw i could download the blockchain, so i downloaded "Wallet_v4.x_Verge-Blockchain_2018-March-25" (copied my wallet to safe location because i thought there should be the coins i previously sent) unzipped it in the APPDATA then i try to open the Wallet APP but once it finished loading the blockchain index it gives me "error loading blkindex.dat".

I tried doing this various times also deleting the Verge folder in the APPDATA and tried again with the 26 March Blockchain. I tried to unzip the blockchain inside the folder and overwrite the files already there and also tried deleting all the files in the folder and just unzipping the blockchain in there. I tried to disable my antivirus. Attached below the log:

[debug.log](https://github.com/vergecurrency/VERGE/files/1855742/debug.log)

As i've said im very new to all this and not very good with computers so I might have done something stupid along the way, but i looked at multiple videos of people doing this operation and everything went all right

**Comment by jrsikors** [comment] 2018-03-28 15:16
So other people have started reporting same problems as well -- with the march 26th bootstrap.

I'm currently testing with the march 28th bootstrap.. but will be a while.

I still think you should continue your sync from scratch -- it might get sync'd quicker than a potential bootstrap issue is identified and resolved.

Sorry man -- was unfortunate you were the first to run into problems !

**Comment by jrsikors** [comment] 2018-03-28 15:43
@pthai112
#657 

@jetpippo 
#658 

consolidating blkindex.dat problems to one issue for easier updates/tracking.

I have notified relevant people to let them know of a potential problem with the bootstrap.

The only workaround is to download the blockchain from scratch (0 blocks) ... it might take a couple days to sync, which we know is brutal.  There's no ETA on when a bootstrap issue will be identified and resolved.  In other words, it might be quicker to take 2-3 days to sync instead of waiting for a bootstrap.

**Comment by jrsikors** [comment] 2018-03-28 15:48
When messing around with your data directory -- remember to back up your wallet.dat to a safe place .. jump drive ideally, somewhere off computer.

To get a "new" data directory, the safest thing is to go rename the old data directory.  IE:
C:\Users\YOU\AppData\Roaming\Verge
**Rename** the Verge folder to **VergeOld**
then start verge-qt again -- and it will create you a brand new data directory.  remember to copy your wallet.dat back to the new data directory eventually.

If you need immediate access to your funds before the QT fully syncs, the best thing to do is those steps ... get your wallet.dat in there... open verge-qt : 
1) go to debug consoole
2)  type walletpassphrase 'YOUR PASSPHRASE HERE BETWEEN SINGLE QUOTES' 600
3)  dumpprivkey YOURVERGEADDRESS

Now you can take that private key and import it into any other verge wallet like Electrum.

**Comment by jrsikors** [comment] 2018-03-28 15:56
per @swat69 -- he identified issues with recent bootstraps.  He will work to resolve.  No ETA though, stand by !

**Comment by swat69** [comment] 2018-03-28 16:39
new file blk0002.dat missing in zip, fixed.
new up-to-date bootstrap 28th ready for download now

**Comment by jrsikors** [comment] 2018-03-28 16:54
Thanks for the quick turnaround @swat69 .

Everyone should go try out the new download at:
https://verge-blockchain.com/

Again -- make sure you back up wallet.dat

Although probably not necessary .. I would strongly advise clearing out your data directory first (except wallet.dat).  

The safe way is to rename verge data folder to verge_old

But the quicker way is to:
  -delete EVERYTHING in your Verge DataDirectory **_EXCEPT WALLET.DAT_** (default is c:\users\YOU\appdata\roaming\verge).
  -download bootstrap from verge-blockchain.com
  -unzip
  -run verge-qt

**Comment by jrsikors** [comment] 2018-03-28 16:59
@pthai112 see previous post from me

**Comment by omdespers** [comment] 2018-03-28 17:20
now i have Timed out waiting for onion hostname. I have disabled firewall and run qt as admin, nothing helps.

**Comment by jrsikors** [comment] 2018-03-28 17:27
definitely a different issue -- are you running any other applications using Tor?

Does removing the blkdata1.dat and blkdata002.dat make your client not time out ?

**Comment by jrsikors** [comment] 2018-03-28 17:31
If you still have your old data directory -- or it's in the recycle bin -- you could always try copying the old
DATADIR\tor folder into the new datadir , and overwrite/replace the new tor folder files.

If the tor folder doesn't exist, even better

**Comment by omdespers** [comment] 2018-03-28 17:51
I don´t know why but after several tries, it worked. Strange behaviour, I tried it 5 times and everytime the error comes up. Between I also cleaned everything with cc cleaner, restarted my laptop and the error comes again. After the 6th try, it worked now and my wallet synced. I have nothing changed between the tries...strange. Thanks anyway

**Comment by kosstick** [comment] 2018-03-28 18:08
I’ll try when I get home. Currently at 30-40 percent (synced)

**Comment by jrsikors** [comment] 2018-03-28 18:10
no prob @omdespers  , glad it worked.   It's not entirely surprising /alarming.  I was actually going to suggest you try to run it like 10x .. and figured it would eventually find something.  Tor can be wonky like that

**Comment by merbals** [comment] 2018-03-28 18:34
Guys you rock!

Confirmed working for me now. Thanks for your support and quick turnaround!

**Comment by jetpippo** [comment] 2018-03-28 22:43
@jrsikors @swat69 
Dear Jeff and Ben,
I just woke up downloaded the new bootstrap, put my wallet in the APPDATA and everything loaded perfectly after I waited some 10 minutes. Thank you so much for your help have an awesome day!

**Comment by kosstick** [comment] 2018-03-29 02:32
Just downloaded the Blockchain for today. (btw it seems to mislabeled as March 29th..). Anyhow..


WORKS LIKE A CHARM!!!! Thanks guys!

**Comment by pthai112** [comment] 2018-03-29 03:26
@jrsikors 
Hi Jeff. I just download and updated QT-Wallet_v4.x_Verge-Blockchain_2018-March-29.zip and result is good. However my coin don't show, I also resys 2 times but result is same. I checked and found coin in verge block chain explorer . How to display it on Verge wallet software?

**Comment by jrsikors** [comment] 2018-03-29 03:38
Are you sure you got the right wallet.dat in there?

go to the help -> debug console

type:
**_scanforalltxns_**

just that, no number after.  It will take about 15-20 minutes to re-scan.  Don't close client it will finish.

**Comment by pthai112** [comment] 2018-03-29 04:31
@jrsikors 
Hi.
Thank your for your guide. Now coin show on wallet.
So problem:
1.QT-Wallet_v4.x_Verge-Blockchain_2018-March-29.zip to update fully sysr
2.Type: scanforalltxns to show coin.

**Comment by jrsikors** [comment] 2018-03-29 13:19
going to close this one up -- sounds like almost everyone is good with the latest bootstrap.

It probably updated from 28th to 29th ... website says its updates every 00:00 with a new copy.. so i think we are good there.

Please feel free to post a new issue if anyone is still having problems with anything

**Closed by jrsikors** 2018-03-29 13:19 UTC
Labels: Multiple Users with Issues
