### ISSUE TITLE
cannot open on OSX running El Capitan

### ISSUE THREAD

**Issue by pyramation** [vergecurrency/VERGE#148] opened 2017-12-28 02:57 UTC
Looks like it could be related to this electrum issue: https://github.com/spesmilo/electrum/issues/2726

When opening the app, it unexpectedly quits, and then I click "report" to get the error message. I've left the error messages for both regular and tor app for OSX below (looks to match the issue from electrum)

```
Dyld Error Message:
  Symbol not found: _getentropy
  Referenced from: /Volumes/VOLUME/Electrum-XVG.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```

```
Dyld Error Message:
  Symbol not found: _getentropy
  Referenced from: /Volumes/*/Electrum-XVG-TOR.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by hershman** [comment] 2017-12-28 06:41
This [open ticket from another project](https://gitlab.com/gnutls/gnutls/issues/142) has more information about the underlying problem caused by Apple and libraries in XCode

**Comment by justinvforvendetta** [comment] 2017-12-28 17:44
you dragged it into applications to open it, or just double clicked the file after downloading?

**Comment by ryan-blake** [comment] 2017-12-28 21:05
After separate downloads I dragged to Apps and clicked the file to open. Electrum still returns the same error for me as well.

**Comment by barshaldhir** [comment] 2017-12-28 22:48
I have had the same issue. I have Electrum installed on my machine for BTC. Do you have it installed too?

**Comment by pyramation** [comment] 2017-12-29 21:06
@justinvforvendetta even if I drag it into the applications folder.

I'm running El Capitan 10.11.6

@ryan-blake and @bars1986 what version OSX are you guys running? Let's try and see if it's an El Capitan issue, so at least there could be a small compatibility disclaimer until the issue is fixed.

**Comment by ryan-blake** [comment] 2017-12-29 23:01
@pyramation same issue with 10.11.6

**Comment by touedraogo** [comment] 2017-12-29 23:19
same issue with 10.11.6

**Comment by bars1986** [comment] 2017-12-30 04:28
@pyramation OS X El Capitan 10.11.6 

As i mentioned I do have another Electrum wallet installed that holds my mBTC.

Thanks for your help.

**Comment by justinvforvendetta** [comment] 2017-12-30 04:37
@bars1986 @touedraogo you dragged the app into applications?

**Comment by bars1986** [comment] 2017-12-30 04:56
yes I dragged it into the Applications folder and I have also tried just double-clicking to open.

**Comment by justinvforvendetta** [comment] 2017-12-30 04:58
double clicking shouldnt work, but dragging into applications should. do you have admin rights on that computer?

**Comment by bars1986** [comment] 2017-12-30 05:08
Yessir. :)

**Comment by touedraogo** [comment] 2017-12-30 08:42
this is what i have done:
- Admin rights 
- Dragged to into application folder
- Go to Finder / Application and not from Lanchpad to avoid message saying that that App is not Official+Apple+Blah
- then right click + open  

Even tried from Terminal console 

[admin@DarkMac:/Applications/Electrum-XVG.app/Contents/MacOS]$ ./Electrum-XVG 
dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /Applications/Electrum-XVG.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: /Applications/Electrum-XVG.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by Hubsi3** [comment] 2017-12-30 12:32
My electrum wallet also crashed on macOS high sierra 10.13.2. It just showed an empty error box. I cloud fix it by just renaming the application (in the applications folder) from "Electrum-XVG.app" to "Electrum.app". Everything's working fine now!

**Comment by SomePoorSlob** [comment] 2017-12-30 22:32
This wallet doesn't open at all for me on El Cap 10.11.6. All the usual stuff mentioned above is ok (admin rights, dragged it to App folder, etc.). When doubleclicking to open, the icon does its little expansion animation, and then nothing whatsoever. It won't launch.

**Comment by ekryski** [comment] 2017-12-30 23:30
I can confirm both @Hubsi3 and @SomePoorSlob's comments. Same deal here. Super weird. Must be a bad reference somewhere???

**Comment by Gh0stKnow** [comment] 2017-12-31 10:05
same issue with 10.11.6

**Comment by dnev1551** [comment] 2017-12-31 10:12
can confirm download and upon opening the Verge OSX Electrum Wallet using Mac OS brings an error...using Mac OS High Sierra Version 10.13.2

**Comment by ekryski** [comment] 2017-12-31 17:58
The new Wraith build doesn't have this issue so once that launches @justinvforvendetta you can probably close this out.

**Comment by fmachadodev** [comment] 2018-01-01 23:56
same error here.

**Comment by aaads** [comment] 2018-01-02 04:30
Attempt at opening OS Electrum Wallet on a MacBook Air (2015) OS X Yosemite = unsuccessful, coming up with the error message via the Screenshot below;

![screen shot 2018-01-02 at 3 25 24 pm](https://user-images.githubusercontent.com/35019850/34474341-91479be0-efd1-11e7-8f48-86678bb3c581.png)

**Comment by burakim** [comment] 2018-01-02 23:26
Can you open a terminal, type "brew config" and send an output of your brew configuration? It might be caused by Python CLT. There are few bug reports that say Xcode 8.0 and python 2.7 are not sometimes working very well. They recommend upgrading your Xcode build tools. If you haven't installed it on your system, you can install it by typing "xcode-select --install". Moreover, if you already installed it your system, you upgrade it from software update app.

**Closed** 2018-01-15 19:44 UTC
